var Showdown={extensions:{}},forEach=Showdown.forEach=function(b,e){if("function"===typeof b.forEach)b.forEach(e);else{var d,h=b.length;for(d=0;d<h;d++)e(b[d],d,b)}},stdExtName=function(b){return b.replace(/[_-]||\s/g,"").toLowerCase()};
Showdown.converter=function(b){var e,d,h,i=0,j=[],l=[];if("undefind"!==typeof module&&"undefined"!==typeof exports&&"undefind"!==typeof require){var r=require("fs");r&&(r=r.readdirSync((__dirname||".")+"/extensions").filter(function(a){return~a.indexOf(".js")}).map(function(a){return a.replace(/\.js$/,"")}),Showdown.forEach(r,function(a){var b=stdExtName(a);Showdown.extensions[b]=require("./extensions/"+a)}))}this.makeHtml=function(a){e={};d={};h=[];a=a.replace(/~/g,"~T");a=a.replace(/\$/g,"~D");
a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");a="\n\n"+a+"\n\n";a=z(a);a=a.replace(/^[ \t]+$/mg,"");Showdown.forEach(j,function(b){a=s(b,a)});var b;b=a+"~0";b=b.replace(/(?:^|\n)```(.*)\n([\s\S]*?)\n```/g,function(a,b,c){a=K(c);a=z(a);a=a.replace(/^\n+/g,"");a=a.replace(/\n+$/g,"");a="<pre><code"+(b?' class="'+b+'"':"")+">"+a+"\n</code></pre>";return y(a)});a=b=b.replace(/~0/,"");a=x(a);b=a+"~0";b=b.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|(?=~0))/gm,
function(a,b,c,f,B){b=b.toLowerCase();e[b]=t(c);if(f)return f+B;B&&(d[b]=B.replace(/"/g,"&quot;"));return""});a=b=b.replace(/~0/,"");a=q(a);a=O(a);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");Showdown.forEach(l,function(b){a=s(b,a)});return a};if(b&&b.extensions){var m=this;Showdown.forEach(b.extensions,function(a){"string"===typeof a&&(a=Showdown.extensions[stdExtName(a)]);if("function"===typeof a)Showdown.forEach(a(m),function(a){a.type?"language"===a.type||"lang"===a.type?j.push(a):("output"===
a.type||"html"===a.type)&&l.push(a):l.push(a)});else throw"Extension '"+a+"' could not be loaded.  It was either not found or is not a valid extension.";})}var s=function(a,b){if(a.regex)return b.replace(RegExp(a.regex,"g"),a.replace);if(a.filter)return a.filter(b)},x=function(a){a=a.replace(/\n/g,"\n\n");a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,f);a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|style|section|header|footer|nav|article|aside)\b[^\r]*?<\/\2>[ \t]*(?=\n+)\n)/gm,
f);a=a.replace(/(\n[ ]{0,3}(<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,f);a=a.replace(/(\n\n[ ]{0,3}<!(--[^\r]*?--\s*)+>[ \t]*(?=\n{2,}))/g,f);a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,f);return a=a.replace(/\n\n/g,"\n")},f=function(a,b){var c;c=b.replace(/\n\n/g,"\n");c=c.replace(/^\n/,"");c=c.replace(/\n+$/g,"");return c="\n\n~K"+(h.push(c)-1)+"K\n\n"},q=function(a){for(var b=function(a){return a.replace(/[^\w]/g,"").toLowerCase()},a=a.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,
function(a,f){return y('<h1 id="'+b(f)+'">'+c(f)+"</h1>")}),a=a.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(a,f){return y('<h2 id="'+b(f)+'">'+c(f)+"</h2>")}),a=a.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,function(a,f,g){a=f.length;return y("<h"+a+' id="'+b(g)+'">'+c(g)+"</h"+a+">")}),f=y("<hr />"),a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,f),a=a.replace(/^[ ]{0,2}([ ]?\-[ ]?){3,}[ \t]*$/gm,f),a=a.replace(/^[ ]{0,2}([ ]?\_[ ]?){3,}[ \t]*$/gm,f),a=n(a),a=a+"~0",a=a.replace(/(?:\n\n|^)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,
function(a,b,c){a=K(v(b));a=z(a);a=a.replace(/^\n+/g,"");a=a.replace(/\n+$/g,"");a="<pre><code>"+a+"\n</code></pre>";return y(a)+c}),a=a.replace(/~0/,""),a=a.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,b){var c;c=b.replace(/^[ \t]*>[ \t]?/gm,"~0");c=c.replace(/~0/g,"");c=c.replace(/^[ \t]+$/gm,"");c=q(c);c=c.replace(/(^|\n)/g,"$1  ");c=c.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,b){var c;c=b.replace(/^  /mg,"~0");return c=c.replace(/~0/g,"")});return y("<blockquote>\n"+c+"\n</blockquote>")}),
a=x(a),a=a.replace(/^\n+/g,""),a=a.replace(/\n+$/g,""),k=a.split(/\n{2,}/g),a=[],f=k.length,d=0;d<f;d++){var g=k[d];0<=g.search(/~K(\d+)K/g)?a.push(g):0<=g.search(/\S/)&&(g=c(g),g=g.replace(/^([ \t]*)/g,"<p>"),g+="</p>",a.push(g))}f=a.length;for(d=0;d<f;d++)for(;0<=a[d].search(/~K(\d+)K/);)k=h[RegExp.$1],k=k.replace(/\$/g,"$$$$"),a[d]=a[d].replace(/~K\d+K/,k);return a=a.join("\n\n")},c=function(a){a=a.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(a,b,c,f){a=f.replace(/^([ \t]*)/g,"");a=a.replace(/[ \t]*$/g,
"");a=K(a);return b+"<code>"+a+"</code>"});a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--.*?--\s*)+>)/gi,function(a){a=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return a=u(a,"\\`*_")});a=a.replace(/\\(\\)/g,A);a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,A);a=a.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,g);a=a.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,g);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,k);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?(.*?(?:\(.*?\).*?)?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,
k);a=a.replace(/(\[([^\[\]]+)\])()()()()()/g,k);a=a.replace(/<((https?|ftp|dict):[^'">\s]+)>/gi,'<a href="$1">$1</a>');a=a.replace(/<(?:mailto:)?([-.\w]+\@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)>/gi,function(a,b){var c=O(b),f=[function(a){return"&#"+a.charCodeAt(0)+";"},function(a){return"&#x"+a.charCodeAt(0).toString(16)+";"},function(a){return a}],c=("mailto:"+c).replace(/./g,function(a){if("@"==a)a=f[Math.floor(2*Math.random())](a);else if(":"!=a)var b=Math.random(),a=0.9<b?f[2](a):0.45<b?f[1](a):f[0](a);
return a}),c='<a href="'+c+'">'+c+"</a>";return c=c.replace(/">.+:/g,'">')});a=t(a);a=a.replace(/(\*\*|__)(?=\S)([^\r]*?\S[*_]*)\1/g,"<strong>$2</strong>");a=a.replace(/(\*|_)(?=\S)([^\r]*?\S)\1/g,"<em>$2</em>");return a=a.replace(/  +\n/g," <br />\n")},k=function(a,b,c,f,g,k,q,h){void 0==h&&(h="");a=f.toLowerCase();if(""==g)if(""==a&&(a=c.toLowerCase().replace(/ ?\n/g," ")),void 0!=e[a])g=e[a],void 0!=d[a]&&(h=d[a]);else if(-1<b.search(/\(\s*\)$/m))g="";else return b;g=u(g,"*_");b='<a href="'+g+
'"';""!=h&&(h=h.replace(/"/g,"&quot;"),h=u(h,"*_"),b+=' title="'+h+'"');return b+(">"+c+"</a>")},g=function(a,b,c,f,g,k,h,q){a=c;f=f.toLowerCase();q||(q="");if(""==g)if(""==f&&(f=a.toLowerCase().replace(/ ?\n/g," ")),void 0!=e[f])g=e[f],void 0!=d[f]&&(q=d[f]);else return b;a=a.replace(/"/g,"&quot;");g=u(g,"*_");b='<img src="'+g+'" alt="'+a+'"';q=q.replace(/"/g,"&quot;");q=u(q,"*_");return b=b+(' title="'+q+'"')+" />"},p,n=function(a){var a=a+"~0",b=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;
i?a=a.replace(b,function(a,b,c){a=b;c=-1<c.search(/[*+-]/g)?"ul":"ol";a=a.replace(/\n{2,}/g,"\n\n\n");a=p(a);a=a.replace(/\s+$/,"");return"<"+c+">"+a+"</"+c+">\n"}):(b=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g,a=a.replace(b,function(a,b,c,f){a=c;f=-1<f.search(/[*+-]/g)?"ul":"ol";a=a.replace(/\n{2,}/g,"\n\n\n");a=p(a);return b+"<"+f+">\n"+a+"</"+f+">\n"}));return a=a.replace(/~0/,"")};p=function(a){i++;a=a.replace(/\n{2,}$/,"\n");a=(a+"~0").replace(/(\n)?(^[ \t]*)([*+-]|\d+[.])[ \t]+([^\r]+?(\n{1,2}))(?=\n*(~0|\2([*+-]|\d+[.])[ \t]+))/gm,
function(a,b,f,g,k){a=k;b||-1<a.search(/\n{2,}/)?a=q(v(a)):(a=n(v(a)),a=a.replace(/\n$/,""),a=c(a));return"<li>"+a+"</li>\n"});a=a.replace(/~0/g,"");i--;return a};var y=function(a){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(h.push(a)-1)+"K\n\n"},K=function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=u(a,"*_{}[]\\",!1)},t=function(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?\$!])/gi,"&lt;")},O=function(a){return a=
a.replace(/~E(\d+)E/g,function(a,b){var c=parseInt(b);return String.fromCharCode(c)})},v=function(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")},z=function(a){a=a.replace(/\t(?=\t)/g,"    ");a=a.replace(/\t/g,"~A~B");a=a.replace(/~B(.+?)~A/g,function(a,b){for(var c=b,f=4-c.length%4,g=0;g<f;g++)c+=" ";return c});a=a.replace(/~A/g,"    ");return a=a.replace(/~B/g,"")},u=function(a,b,c){b="(["+b.replace(/([\[\]\\])/g,"\\$1")+"])";c&&(b="\\\\"+b);return a=a.replace(RegExp(b,"g"),
A)},A=function(a,b){return"~E"+b.charCodeAt(0)+"E"}};"undefined"!==typeof module&&(module.exports=Showdown);"function"===typeof define&&define.amd&&define("showdown",function(){return Showdown});(function(b){function e(d){if("string"===typeof d.data){var h=d.handler,e=d.data.toLowerCase().split(" ");d.handler=function(d){if(!(this!==d.target&&(/textarea|select/i.test(d.target.nodeName)||"text"===d.target.type))){var l="keypress"!==d.type&&b.hotkeys.specialKeys[d.which],r=String.fromCharCode(d.which).toLowerCase(),m="",s={};d.altKey&&"alt"!==l&&(m+="alt+");d.ctrlKey&&"ctrl"!==l&&(m+="ctrl+");d.metaKey&&(!d.ctrlKey&&"meta"!==l)&&(m+="meta+");d.shiftKey&&"shift"!==l&&(m+="shift+");l?s[m+l]=
!0:(s[m+r]=!0,s[m+b.hotkeys.shiftNums[r]]=!0,"shift+"===m&&(s[b.hotkeys.shiftNums[r]]=!0));l=0;for(r=e.length;l<r;l++)if(s[e[l]])return h.apply(this,arguments)}}}}b.hotkeys={version:"0.8",specialKeys:{8:"backspace",9:"tab",13:"return",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"capslock",27:"esc",32:"space",33:"pageup",34:"pagedown",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"del",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",106:"*",107:"+",
109:"-",110:".",111:"/",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",144:"numlock",145:"scroll",191:"/",224:"meta"},shiftNums:{"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(","0":")","-":"_","=":"+",";":": ","'":'"',",":"<",".":">","/":"?","\\":"|"}};b.each(["keydown","keyup","keypress"],function(){b.event.special[this]={add:e}})})(jQuery);var relativeDate=function(b){var e=[[42E3,"just now"],[9E4,"a minute ago"],[36E5,"minutes ago",6E4],[54E5,"an hour ago"],[864E5,"hours ago",36E5],[1728E5,"yesterday"],[6048E5,"days ago",864E5],[9072E5,"a week ago"],[2628E6,"weeks ago",6048E5],[3942E6,"a month ago"],[31536E6,"months ago",2628E6],[47304E6,"a year ago"],[Number.MAX_VALUE,"years ago",31536E6]];return function(d,h){!h&&(h=(new Date).getTime());h instanceof Date&&(h=h.getTime());d instanceof Date&&(d=d.getTime());var i=h-d,j,l,r;l=-1;for(r=
e.length;++l<r;)if(j=e[l],i<j[0])return j[2]==b?j[1]:Math.round(i/j[2])+" "+j[1]}}();"undefined"!=typeof module&&module.exports&&(module.exports=relativeDate);function engine(b){var e=new Showdown.converter;!b.type&&b.src&&(b.src.match(".md$")?b.type="markdown":b.src.match(".html$")?b.type="html":b.src.match("rss|atom$")?b.type="rss":b.src.match(/manifest\.json$/)&&(b.type="blog"));if(!b.src)return console.log("src required",b);if(b.target)b.target=$(b.target);else return console.log("target DOM element required",b);this.target=b.target;var d=[],h=!1,i=!1,j={};j.rss=j.atom=function(b,d){$.ajax({url:"https://ajax.googleapis.com/ajax/services/feed/load",
data:{v:"1.0",q:b,num:-1},type:"GET",dataType:"jsonp",error:function(b,f){d(f)},success:function(b){if(b.responseDetails)return console.log(b.responseDetails);var b=b.responseData.feed.entries,f=[],q;for(q in b)f[q]={title:b[q].title,url:b[q].link,html:b[q].content,date:b[q].publishedDate,author:b[q].author,type:"blog"};d(f)}})};j.blog=function(b,d){$.ajax({url:b,success:function(e){var f=b.replace(/[^\/]*$/,""),q=[],c;for(c in e)e[c].src=f+e[c].src,q[c]=function(b){return function(c){j.markdown(b.src,
function(f){f[0].type="blog";f[0].title=b.title?b.title:b.src.match(/([^\/]+)\.[^.]+$/)[1];f[0].date=b.date;f[0].author=b.author;c(f[0])})}}(e[c]);d(q)},error:function(b,f){d(f)},dataType:"json"})};j.raw=j.html=function(b,d){$.ajax({url:b,dataType:"html",error:function(b,f){d(f)},success:function(b){d([{html:b}])}})};j.markdown=function(b,d){j.raw(b,function(b){b[0].html=e.makeHtml(b[0].html);d(b)})};var l=this.render=function(){if(d.length){h=!0;var e=$("<section />").appendTo(b.target),j=d.shift();
if("object"==typeof j)var i=j,j=function(b){b(i)};else e.html('<div class="throbber"></div>');j(function(b){e.html(b.html).addClass(b.type);var d=$("<h1 />").prependTo(e).text(b.title);b.title&&e.append("<hr />");if(b.url){var c=$("<a />").attr("target","_new").attr("href",b.url);d.wrapInner(c).append(" &raquo;")}b.date&&$("<time />").attr("datetime",b.date).text(relativeDate(new Date(b.date))).appendTo(d);b.author&&$("<span />").addClass("note").text(" by ").append(b.author).appendTo(d);$("pre code",
e).each(function(b,c){hljs.highlightBlock(c)});h=!1})}},r=this.evaluate=function(){if(!h&&i&&$("section:visible",b.target).length){if(0==d.length)return $(window).unbind("scroll",r);$(window).scrollTop()>$("section",b.target).last().offset().top-$(window).height()&&l()}};setInterval(function(){$("time[datetime]",b.target).each(function(){var b=new Date($(this).attr("datetime"));$(this).text(relativeDate(b))})},3E4);j[b.type](b.src,function(e){d=e;b.target.empty();$(window).scroll(r);l();i=!0})};$(function(){animations();generateNav();hotkeys()});
function generateNav(){$("nav").empty();$("article[data-name]").each(function(b,e){var e=$(e),d="#"+e.data("name").replace(/[^0-9a-z]+/gi,"-"),h=$("<a />").addClass("service");h.text(e.data("name"));h.appendTo("nav");h.click(showThisArticle);h.one("mouseenter",function(){initArticle(e)});h.data("article",e);h.attr("href",d);!e.data("download")&&e.data("type")&&e.data("type").match(/rss|atom/)&&e.data("download",e.data("src"));h.attr("title",e.data("hint"));document.location.hash==d&&h.each(showThisArticle);
e.hasClass("default")&&1>=document.location.hash.length&&h.each(showThisArticle)})}function showThisArticle(){var b=$(this).data("article");$("article").hide();b.show().text();$("nav .service").removeClass("active");$(this).addClass("active");if(!b.hasClass("default")||document.location.hash)document.location.hash=$(this).attr("href");$(".articles header").html(b.data("hint"));initArticle(b)}function preloadArticles(){$("article[data-preload]").each(function(){initArticle($(this))})}
function initArticle(b){if(b.data("engine")||!b.data("src"))return!1;b.data("engine",new engine({src:b.data("src"),target:b,type:b.data("type")}))}
function animations(){$("article[data-src]").html('<div class="throbber"></div>');$("#backdrop > img").hide().bind("load",function(){$(this).fadeIn(3500);preloadArticles()});$("article .logos img").css("opacity",0).load(function(){$(this).fadeTo("fast",0.7)});$("#contact,#backtotop").hide();var b=function(){$("#logo .quote").stop().fadeOut();$("#logo h1").stop().animate({"margin-top":"50px"})};setTimeout(function(){b();$("#logo").bind("mouseleave",b)},4E3);$("#logo").bind("mouseenter",function(){$("#logo .quote").stop().fadeIn();
$("#logo h1").stop().animate({"margin-top":"26px"})});var e=setTimeout(function(){$("#contact").hide().fadeIn()},6E3);$(window).one("scroll",function(){clearTimeout(e);$("#contact").fadeIn()});var d=!1;$(window).on("scroll",function(){500<$(window).scrollTop()?(d||$("#backtotop").stop().slideDown(),d=!0):(d&&$("#backtotop").stop().slideUp(),d=!1)});$.browser.msie&&9<=parseInt($.browser.version)&&setTimeout(function(){$("img").trigger("load")},3E3)}
function hotkeys(){$(document).bind("keydown","right",function(){($(".service").hasClass("active")?$(".active").next():$(".service").first()).each(showThisArticle)});$(document).bind("keydown","left",function(){($(".service").hasClass("active")?$(".active").prev():$(".service").first()).each(showThisArticle)});$(document).bind("keyup","return",function(){$("nav a.active").each(function(){$(".active").css("top",0);var b=$(this).data("article");b.data("download")&&window.open(b.data("download"))})}).bind("keydown",
"return",function(){$(".active").css("position","relative").css("top","2px")});var b=function(){$("body").animate({scrollTop:0})};$("#backtotop").click(b);$(document).bind("keydown","t",b)};var hljs=new function(){function b(b){return b.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function e(b,d,c){return RegExp(d,"m"+(b.cI?"i":"")+(c?"g":""))}function d(b,e){for(var c="",k=0;k<b.childNodes.length;k++)if(3==b.childNodes[k].nodeType){var g=b.childNodes[k].nodeValue;e&&(g=g.replace(/\n/g,""));c+=g}else c="BR"==b.childNodes[k].nodeName?c+"\n":c+d(b.childNodes[k]);/MSIE [678]/.test(navigator.userAgent)&&(c=c.replace(/\r/g,"\n"));return c}function h(b){var d=[];(function(b,f){for(var g=0;g<
b.childNodes.length;g++)3==b.childNodes[g].nodeType?f+=b.childNodes[g].nodeValue.length:"BR"==b.childNodes[g].nodeName?f+=1:1==b.childNodes[g].nodeType&&(d.push({event:"start",offset:f,node:b.childNodes[g]}),f=arguments.callee(b.childNodes[g],f),d.push({event:"stop",offset:f,node:b.childNodes[g]}));return f})(b,0);return d}function i(){function b(c,d,g){if(!c.compiled){g||(c.bR=e(d,c.b?c.b:"\\B|\\b"),!c.e&&!c.eW&&(c.e="\\B|\\b"),c.e&&(c.eR=e(d,c.e)));c.i&&(c.iR=e(d,c.i));void 0===c.r&&(c.r=1);if(c.k){c.lR=
e(d,c.l||hljs.IR,!0);for(var h in c.k)if(c.k.hasOwnProperty(h)){c.k[h]instanceof Object?g=c.k[h]:(g=c.k,h="keyword");for(var q in g)g.hasOwnProperty(q)&&(c.k[q]=[h,g[q]])}}c.c||(c.c=[]);c.compiled=!0;for(h=0;h<c.c.length;h++)"self"==c.c[h]&&(c.c[h]=c),b(c.c[h],d,!1);c.starts&&b(c.starts,d,!1)}}for(var d in x)x.hasOwnProperty(d)&&b(x[d].dM,x[d],!0)}function j(d,h){function c(a,b){if(n[a].e&&n[a].eR.test(b))return 1;if(n[a].eW){var d=c(a-1,b);return d?d+1:0}return 0}function k(a,c){if(c.sL&&x[c.sL]){var d=
j(c.sL,a);l+=d.keyword_count;return d.value}d=b(a);if(c.k){var f="",g=0;c.lR.lastIndex=0;for(var h=c.lR.exec(d);h;){var f=f+d.substr(g,h.index-g),g=c,e=h,e=p.cI?e[0].toLowerCase():e[0];(g=(g=g.k[e])&&g instanceof Array?g:!1)?(l+=g[1],f+='<span class="'+g[0]+'">'+h[0]+"</span>"):f+=h[0];g=c.lR.lastIndex;h=c.lR.exec(d)}d=f+d.substr(g,d.length-g)}return d}function g(a,c){var d=a.cN?'<span class="'+a.cN+'">':"";a.rB?(t+=d,a.buffer=""):a.eB?(t+=b(c)+d,a.buffer=""):(t+=d,a.buffer=c);n.push(a);y+=a.r}i.called||
(i(),i.called=!0);var p=x[d],n=[p.dM],y=0,l=0,t="";try{var r,v=0;p.dM.buffer="";do{var m=h,u=v,s=n[n.length-1];if(!s.t){for(var a=s,B,H=s,R=p,I=[],L=0;L<H.c.length;L++)I.push(H.c[L].b);var J=n.length-1;do n[J].e&&I.push(n[J].e),J--;while(n[J+1].eW);H.i&&I.push(H.i);B=e(R,"("+I.join("|")+")",!0);a.t=B}s.t.lastIndex=u;var M=s.t.exec(m);r=M?[m.substr(u,M.index-u),M[0],!1]:[m.substr(u),"",!0];var D;var E=r[0],C=r[1],w=n[n.length-1];if(r[2])t+=k(w.buffer+E,w),D=!1;else{var F;b:{m=C;u=w;for(a=0;a<u.c.length;a++)if(u.c[a].bR.test(m)){F=
u.c[a];break b}F=void 0}if(F)t+=k(w.buffer+E,w),g(F,C),D=F.rB;else{var N=c(n.length-1,C);if(N){for(var G=w.cN?"</span>":"",t=w.rE?t+(k(w.buffer+E,w)+G):w.eE?t+(k(w.buffer+E,w)+G+b(C)):t+(k(w.buffer+E+C,w)+G);1<N;)G=n[n.length-2].cN?"</span>":"",t+=G,N--,n.length--;var P=n[n.length-1];n.length--;n[n.length-1].buffer="";P.starts&&g(P.starts,"");D=w.rE}else{if(w.i&&w.iR.test(C))throw"Illegal";D=void 0}}}v+=r[0].length;D||(v+=r[1].length)}while(!r[2]);if(1<n.length)throw"Illegal";return{r:y,keyword_count:l,
value:t}}catch(Q){if("Illegal"==Q)return{r:0,keyword_count:0,value:b(h)};throw Q;}}function l(d){var h={keyword_count:0,r:0,value:b(d)},c=h,e;for(e in x)if(x.hasOwnProperty(e)){var g=j(e,d);g.language=e;g.keyword_count+g.r>c.keyword_count+c.r&&(c=g);g.keyword_count+g.r>h.keyword_count+h.r&&(c=h,h=g)}c.language&&(h.second_best=c);return h}function r(b,d,c){d&&(b=b.replace(/^((<[^>]+>|\t)+)/gm,function(b,c){return c.replace(/\t/g,d)}));c&&(b=b.replace(/\n/g,"<br>"));return b}function m(f,e,c){var k=
d(f,c),g;a:{var p=f;g=p.className.split(/\s+/);g=g.concat(p.parentNode.className.split(/\s+/));for(p=0;p<g.length;p++){var n=g[p].replace(/^language-/,"");if(x[n]||"no-highlight"==n){g=n;break a}}g=void 0}var i;if("no-highlight"!=g){g?p=j(g,k):(p=l(k),g=p.language);var m=h(f);if(m.length){i=document.createElement("pre");i.innerHTML=p.value;n=p;i=h(i);for(var t=function(a){for(var c="<"+a.nodeName.toLowerCase(),d=0;d<a.attributes.length;d++){var f=a.attributes[d],c=c+(" "+f.nodeName.toLowerCase());
void 0!==f.value&&(!1!==f.value&&null!==f.value)&&(c+='="'+b(f.value)+'"')}return c+">"},s=0,v="",z=[];m.length||i.length;){var u=(m.length&&i.length?m[0].offset!=i[0].offset?m[0].offset<i[0].offset?m:i:"start"==i[0].event?m:i:m.length?m:i).splice(0,1)[0],v=v+b(k.substr(s,u.offset-s)),s=u.offset;if("start"==u.event)v+=t(u.node),z.push(u.node);else if("stop"==u.event){var A,a=z.length;do a--,A=z[a],v+="</"+A.nodeName.toLowerCase()+">";while(A!=u.node);for(z.splice(a,1);a<z.length;)v+=t(z[a]),a++}}k=
v+b(k.substr(s));n.value=k}p.value=r(p.value,e,c);e=f.className;e.match("(\\s|^)(language-)?"+g+"(\\s|$)")||(e=e?e+" "+g:g);/MSIE [678]/.test(navigator.userAgent)&&"CODE"==f.tagName&&"PRE"==f.parentNode.tagName?(i=f.parentNode,c=document.createElement("div"),c.innerHTML="<pre><code>"+p.value+"</code></pre>",f=c.firstChild.firstChild,c.firstChild.cN=i.cN,i.parentNode.replaceChild(c.firstChild,i)):f.innerHTML=p.value;f.className=e;f.result={language:g,kw:p.keyword_count,re:p.r};p.second_best&&(f.second_best=
{language:p.second_best.language,kw:p.second_best.keyword_count,re:p.second_best.r})}}function s(){if(!s.called){s.called=!0;for(var b=document.getElementsByTagName("pre"),d=0;d<b.length;d++){var c;a:{c=b[d];for(var e=0;e<c.childNodes.length;e++){var g=c.childNodes[e];if("CODE"==g.nodeName){c=g;break a}if(!(3==g.nodeType&&g.nodeValue.match(/\s+/)))break}c=void 0}c&&m(c,hljs.tabReplace)}}}var x={};this.LANGUAGES=x;this.highlight=j;this.highlightAuto=l;this.fixMarkup=r;this.highlightBlock=m;this.initHighlighting=
s;this.initHighlightingOnLoad=function(){window.addEventListener?(window.addEventListener("DOMContentLoaded",s,!1),window.addEventListener("load",s,!1)):window.attachEvent?window.attachEvent("onload",s):window.onload=s};this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BINARY_NUMBER_RE="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";
this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BINARY_NUMBER_MODE={cN:"number",b:this.BINARY_NUMBER_RE,r:0};this.inherit=function(b,d){var c={},e;for(e in b)c[e]=b[e];if(d)for(e in d)c[e]=d[e];return c}};
hljs.LANGUAGES.bash=function(){var b={"true":1,"false":1},e={cN:"variable",b:"\\$([a-zA-Z0-9_]+)\\b"},d={cN:"variable",b:"\\$\\{(([^}])|(\\\\}))+\\}",c:[hljs.CNM]},h={cN:"string",b:'"',e:'"',i:"\\n",c:[hljs.BE,e,d],r:0},i={cN:"string",b:"'",e:"'",r:0},j={cN:"test_condition",b:"",e:"",c:[h,i,e,d,hljs.CNM],k:{literal:b},r:0};return{dM:{k:{keyword:{"if":1,then:1,"else":1,fi:1,"for":1,"break":1,"continue":1,"while":1,"in":1,"do":1,done:1,echo:1,exit:1,"return":1,set:1,declare:1},literal:b},c:[{cN:"shebang",
b:"(#!\\/bin\\/bash)|(#!\\/bin\\/sh)",r:10},e,d,hljs.HCM,hljs.CNM,h,i,hljs.inherit(j,{b:"\\[ ",e:" \\]",r:0}),hljs.inherit(j,{b:"\\[\\[ ",e:" \\]\\]"})]}}}();
hljs.LANGUAGES.cs={dM:{k:{"abstract":1,as:1,base:1,bool:1,"break":1,"byte":1,"case":1,"catch":1,"char":1,checked:1,"class":1,"const":1,"continue":1,decimal:1,"default":1,delegate:1,"do":1,"double":1,"else":1,"enum":1,event:1,explicit:1,extern:1,"false":1,"finally":1,fixed:1,"float":1,"for":1,foreach:1,"goto":1,"if":1,implicit:1,"in":1,"int":1,"interface":1,internal:1,is:1,lock:1,"long":1,namespace:1,"new":1,"null":1,object:1,operator:1,out:1,override:1,params:1,"private":1,"protected":1,"public":1,
readonly:1,ref:1,"return":1,sbyte:1,sealed:1,"short":1,sizeof:1,stackalloc:1,"static":1,string:1,struct:1,"switch":1,"this":1,"throw":1,"true":1,"try":1,"typeof":1,uint:1,ulong:1,unchecked:1,unsafe:1,ushort:1,using:1,virtual:1,"volatile":1,"void":1,"while":1,ascending:1,descending:1,from:1,get:1,group:1,into:1,join:1,let:1,orderby:1,partial:1,select:1,set:1,value:1,"var":1,where:1,yield:1},c:[{cN:"comment",b:"///",e:"$",rB:!0,c:[{cN:"xmlDocTag",b:"///|<\!--|--\>"},{cN:"xmlDocTag",b:"</?",e:">"}]},
hljs.CLCM,hljs.CBLCLM,{cN:"preprocessor",b:"#",e:"$",k:{"if":1,"else":1,elif:1,endif:1,define:1,undef:1,warning:1,error:1,line:1,region:1,endregion:1,pragma:1,checksum:1}},{cN:"string",b:'@"',e:'"',c:[{b:'""'}]},hljs.ASM,hljs.QSM,hljs.CNM]}};
hljs.LANGUAGES.ruby=function(){var b={keyword:{and:1,"false":1,then:1,defined:1,module:1,"in":1,"return":1,redo:1,"if":1,BEGIN:1,retry:1,end:1,"for":1,"true":1,self:1,when:1,next:1,until:1,"do":1,begin:1,unless:1,END:1,rescue:1,nil:1,"else":1,"break":1,undef:1,not:1,"super":1,"class":1,"case":1,require:1,yield:1,alias:1,"while":1,ensure:1,elsif:1,or:1,def:1},keymethods:{__id__:1,__send__:1,abort:1,abs:1,"all?":1,allocate:1,ancestors:1,"any?":1,arity:1,assoc:1,at:1,at_exit:1,autoload:1,"autoload?":1,
"between?":1,binding:1,binmode:1,"block_given?":1,call:1,callcc:1,caller:1,capitalize:1,"capitalize!":1,casecmp:1,"catch":1,ceil:1,center:1,chomp:1,"chomp!":1,chop:1,"chop!":1,chr:1,"class":1,class_eval:1,"class_variable_defined?":1,class_variables:1,clear:1,clone:1,close:1,close_read:1,close_write:1,"closed?":1,coerce:1,collect:1,"collect!":1,compact:1,"compact!":1,concat:1,"const_defined?":1,const_get:1,const_missing:1,const_set:1,constants:1,count:1,crypt:1,"default":1,default_proc:1,"delete":1,
"delete!":1,delete_at:1,delete_if:1,detect:1,display:1,div:1,divmod:1,downcase:1,"downcase!":1,downto:1,dump:1,dup:1,each:1,each_byte:1,each_index:1,each_key:1,each_line:1,each_pair:1,each_value:1,each_with_index:1,"empty?":1,entries:1,eof:1,"eof?":1,"eql?":1,"equal?":1,eval:1,exec:1,exit:1,"exit!":1,extend:1,fail:1,fcntl:1,fetch:1,fileno:1,fill:1,find:1,find_all:1,first:1,flatten:1,"flatten!":1,floor:1,flush:1,for_fd:1,foreach:1,fork:1,format:1,freeze:1,"frozen?":1,fsync:1,getc:1,gets:1,global_variables:1,
grep:1,gsub:1,"gsub!":1,"has_key?":1,"has_value?":1,hash:1,hex:1,id:1,include:1,"include?":1,included_modules:1,index:1,indexes:1,indices:1,induced_from:1,inject:1,insert:1,inspect:1,instance_eval:1,instance_method:1,instance_methods:1,"instance_of?":1,"instance_variable_defined?":1,instance_variable_get:1,instance_variable_set:1,instance_variables:1,"integer?":1,intern:1,invert:1,ioctl:1,"is_a?":1,isatty:1,"iterator?":1,join:1,"key?":1,keys:1,"kind_of?":1,lambda:1,last:1,length:1,lineno:1,ljust:1,
load:1,local_variables:1,loop:1,lstrip:1,"lstrip!":1,map:1,"map!":1,match:1,max:1,"member?":1,merge:1,"merge!":1,method:1,"method_defined?":1,method_missing:1,methods:1,min:1,module_eval:1,modulo:1,name:1,nesting:1,"new":1,next:1,"next!":1,"nil?":1,nitems:1,"nonzero?":1,object_id:1,oct:1,open:1,pack:1,partition:1,pid:1,pipe:1,pop:1,popen:1,pos:1,prec:1,prec_f:1,prec_i:1,print:1,printf:1,private_class_method:1,private_instance_methods:1,"private_method_defined?":1,private_methods:1,proc:1,protected_instance_methods:1,
"protected_method_defined?":1,protected_methods:1,public_class_method:1,public_instance_methods:1,"public_method_defined?":1,public_methods:1,push:1,putc:1,puts:1,quo:1,raise:1,rand:1,rassoc:1,read:1,read_nonblock:1,readchar:1,readline:1,readlines:1,readpartial:1,rehash:1,reject:1,"reject!":1,remainder:1,reopen:1,replace:1,require:1,"respond_to?":1,reverse:1,"reverse!":1,reverse_each:1,rewind:1,rindex:1,rjust:1,round:1,rstrip:1,"rstrip!":1,scan:1,seek:1,select:1,send:1,set_trace_func:1,shift:1,singleton_method_added:1,
singleton_methods:1,size:1,sleep:1,slice:1,"slice!":1,sort:1,"sort!":1,sort_by:1,split:1,sprintf:1,squeeze:1,"squeeze!":1,srand:1,stat:1,step:1,store:1,strip:1,"strip!":1,sub:1,"sub!":1,succ:1,"succ!":1,sum:1,superclass:1,swapcase:1,"swapcase!":1,sync:1,syscall:1,sysopen:1,sysread:1,sysseek:1,system:1,syswrite:1,taint:1,"tainted?":1,tell:1,test:1,"throw":1,times:1,to_a:1,to_ary:1,to_f:1,to_hash:1,to_i:1,to_int:1,to_io:1,to_proc:1,to_s:1,to_str:1,to_sym:1,tr:1,"tr!":1,tr_s:1,"tr_s!":1,trace_var:1,
transpose:1,trap:1,truncate:1,"tty?":1,type:1,ungetc:1,uniq:1,"uniq!":1,unpack:1,unshift:1,untaint:1,untrace_var:1,upcase:1,"upcase!":1,update:1,upto:1,"value?":1,values:1,values_at:1,warn:1,write:1,write_nonblock:1,"zero?":1,zip:1}},e={cN:"yardoctag",b:"@[A-Za-z]+"},d=[{cN:"comment",b:"#",e:"$",c:[e]},{cN:"comment",b:"^\\=begin",e:"^\\=end",c:[e],r:10},{cN:"comment",b:"^__END__",e:"\\n$"}],e={cN:"subst",b:"#\\{",e:"}",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b},h=[hljs.BE,e],i=[{cN:"string",b:"'",
e:"'",c:h,r:0},{cN:"string",b:'"',e:'"',c:h,r:0},{cN:"string",b:"%[qw]?\\(",e:"\\)",c:h,r:10},{cN:"string",b:"%[qw]?\\[",e:"\\]",c:h,r:10},{cN:"string",b:"%[qw]?{",e:"}",c:h,r:10},{cN:"string",b:"%[qw]?<",e:">",c:h,r:10},{cN:"string",b:"%[qw]?/",e:"/",c:h,r:10},{cN:"string",b:"%[qw]?%",e:"%",c:h,r:10},{cN:"string",b:"%[qw]?-",e:"-",c:h,r:10},{cN:"string",b:"%[qw]?\\|",e:"\\|",c:h,r:10}],h={cN:"function",b:"\\bdef\\s+",e:" |$|;",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b,c:[{cN:"title",b:"[a-zA-Z_]\\w*[!?=]?|[-+~]\\@|<<|>>|=~|===?|<=>|[<>]=?|\\*\\*|[-/+%^&*~`|]|\\[\\]=?",
l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b},{cN:"params",b:"\\(",e:"\\)",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b}].concat(d)},j={cN:"identifier",b:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b,r:0},d=d.concat(i.concat([{cN:"class",b:"\\b(class|module)\\b",e:"$|;",k:{"class":1,module:1},c:[{cN:"title",b:"[A-Za-z_]\\w*(::\\w+)*(\\?|\\!)?",r:0},{cN:"inheritance",b:"<\\s*",c:[{cN:"parent",b:"("+hljs.IR+"::)?"+hljs.IR}]}].concat(d)},h,{cN:"constant",b:"(::)?([A-Z]\\w*(::)?)+",
r:0},{cN:"symbol",b:":",c:i.concat([j]),r:0},{cN:"number",b:"(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b",r:0},{cN:"number",b:"\\?\\w"},{cN:"variable",b:"(\\$\\W)|((\\$|\\@\\@?)(\\w+))"},j,{b:"("+hljs.RSR+")\\s*",c:d.concat([{cN:"regexp",b:"/",e:"/[a-z]*",i:"\\n",c:[hljs.BE]}]),r:0}]));e.c=d;h.c[1].c=d;return{dM:{l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b,c:d}}}();
hljs.LANGUAGES.diff={cI:!0,dM:{c:[{cN:"chunk",b:"^\\@\\@ +\\-\\d+,\\d+ +\\+\\d+,\\d+ +\\@\\@$",r:10},{cN:"chunk",b:"^\\*\\*\\* +\\d+,\\d+ +\\*\\*\\*\\*$",r:10},{cN:"chunk",b:"^\\-\\-\\- +\\d+,\\d+ +\\-\\-\\-\\-$",r:10},{cN:"header",b:"Index: ",e:"$"},{cN:"header",b:"=====",e:"=====$"},{cN:"header",b:"^\\-\\-\\-",e:"$"},{cN:"header",b:"^\\*{3} ",e:"$"},{cN:"header",b:"^\\+\\+\\+",e:"$"},{cN:"header",b:"\\*{5}",e:"\\*{5}$"},{cN:"addition",b:"^\\+",e:"$"},{cN:"deletion",b:"^\\-",e:"$"},{cN:"change",
b:"^\\!",e:"$"}]}};
hljs.LANGUAGES.javascript={dM:{k:{keyword:{"in":1,"if":1,"for":1,"while":1,"finally":1,"var":1,"new":1,"function":1,"do":1,"return":1,"void":1,"else":1,"break":1,"catch":1,"instanceof":1,"with":1,"throw":1,"case":1,"default":1,"try":1,"this":1,"switch":1,"continue":1,"typeof":1,"delete":1},literal:{"true":1,"false":1,"null":1}},c:[hljs.ASM,hljs.QSM,hljs.CLCM,hljs.CBLCLM,hljs.CNM,{b:"("+hljs.RSR+"|case|return|throw)\\s*",k:{"return":1,"throw":1,"case":1},c:[hljs.CLCM,hljs.CBLCLM,{cN:"regexp",b:"/",
e:"/[gim]*",c:[{b:"\\\\/"}]}],r:0},{cN:"function",b:"\\bfunction\\b",e:"{",k:{"function":1},c:[{cN:"title",b:"[A-Za-z$_][0-9A-Za-z$_]*"},{cN:"params",b:"\\(",e:"\\)",c:[hljs.ASM,hljs.QSM,hljs.CLCM,hljs.CBLCLM]}]}]}};
hljs.LANGUAGES.css=function(){var b={cN:"function",b:hljs.IR+"\\(",e:"\\)",c:[{eW:!0,eE:!0,c:[hljs.NM,hljs.ASM,hljs.QSM]}]};return{cI:!0,dM:{i:"[=/|']",c:[hljs.CBLCLM,{cN:"id",b:"\\#[A-Za-z0-9_-]+"},{cN:"class",b:"\\.[A-Za-z0-9_-]+",r:0},{cN:"attr_selector",b:"\\[",e:"\\]",i:"$"},{cN:"pseudo",b:":(:)?[a-zA-Z0-9\\_\\-\\+\\(\\)\\\"\\']+"},{cN:"at_rule",b:"@(font-face|page)",l:"[a-z-]+",k:{"font-face":1,page:1}},{cN:"at_rule",b:"@",e:"[{;]",eE:!0,k:{"import":1,page:1,media:1,charset:1},c:[b,hljs.ASM,
hljs.QSM,hljs.NM]},{cN:"tag",b:hljs.IR,r:0},{cN:"rules",b:"{",e:"}",i:"[^\\s]",r:0,c:[hljs.CBLCLM,{cN:"rule",b:"[^\\s]",rB:!0,e:";",eW:!0,c:[{cN:"attribute",b:"[A-Z\\_\\.\\-]+",e:":",eE:!0,i:"[^\\s]",starts:{cN:"value",eW:!0,eE:!0,c:[b,hljs.NM,hljs.QSM,hljs.ASM,hljs.CBLCLM,{cN:"hexcolor",b:"\\#[0-9A-F]+"},{cN:"important",b:"!important"}]}}]}]}]}}}();
hljs.LANGUAGES.xml=function(){var b={eW:!0,c:[{cN:"attribute",b:"[A-Za-z0-9\\._:-]+",r:0},{b:'="',rB:!0,e:'"',c:[{cN:"value",b:'"',eW:!0}]},{b:"='",rB:!0,e:"'",c:[{cN:"value",b:"'",eW:!0}]},{b:"=",c:[{cN:"value",b:"[^\\s/>]+"}]}]};return{cI:!0,dM:{c:[{cN:"pi",b:"<\\?",e:"\\?>",r:10},{cN:"doctype",b:"<!DOCTYPE",e:">",r:10,c:[{b:"\\[",e:"\\]"}]},{cN:"comment",b:"<\!--",e:"--\>",r:10},{cN:"cdata",b:"<\\!\\[CDATA\\[",e:"\\]\\]>",r:10},{cN:"tag",b:"<style(?=\\s|>|$)",e:">",k:{title:{style:1}},c:[b],starts:{cN:"css",
e:"</style>",rE:!0,sL:"css"}},{cN:"tag",b:"<script(?=\\s|>|$)",e:">",k:{title:{script:1}},c:[b],starts:{cN:"javascript",e:"<\/script>",rE:!0,sL:"javascript"}},{cN:"vbscript",b:"<%",e:"%>",sL:"vbscript"},{cN:"tag",b:"</?",e:"/?>",c:[{cN:"title",b:"[^ />]+"},b]}]}}}();
hljs.LANGUAGES.java={dM:{k:{"false":1,"synchronized":1,"int":1,"abstract":1,"float":1,"private":1,"char":1,"interface":1,"boolean":1,"static":1,"null":1,"if":1,"const":1,"for":1,"true":1,"while":1,"long":1,"throw":1,strictfp:1,"finally":1,"protected":1,"extends":1,"import":1,"native":1,"final":1,"implements":1,"return":1,"void":1,"enum":1,"else":1,"break":1,"transient":1,"new":1,"catch":1,"instanceof":1,"byte":1,"super":1,"class":1,"volatile":1,"case":1,assert:1,"short":1,"package":1,"default":1,
"double":1,"public":1,"try":1,"this":1,"switch":1,"continue":1,"throws":1},c:[{cN:"javadoc",b:"/\\*\\*",e:"\\*/",c:[{cN:"javadoctag",b:"@[A-Za-z]+"}],r:10},hljs.CLCM,hljs.CBLCLM,hljs.ASM,hljs.QSM,{cN:"class",b:"(class |interface )",e:"{",k:{"class":1,"interface":1},i:":",c:[{b:"(implements|extends)",k:{"extends":1,"implements":1},r:10},{cN:"title",b:hljs.UIR}]},hljs.CNM,{cN:"annotation",b:"@[A-Za-z]+"}]}};
hljs.LANGUAGES.php={cI:!0,dM:{k:{and:1,include_once:1,list:1,"abstract":1,global:1,"private":1,echo:1,"interface":1,as:1,"static":1,endswitch:1,array:1,"null":1,"if":1,endwhile:1,or:1,"const":1,"for":1,endforeach:1,self:1,"var":1,"while":1,isset:1,"public":1,"protected":1,exit:1,foreach:1,"throw":1,elseif:1,"extends":1,include:1,__FILE__:1,empty:1,require_once:1,"function":1,"do":1,xor:1,"return":1,"implements":1,parent:1,clone:1,use:1,__CLASS__:1,__LINE__:1,"else":1,"break":1,print:1,eval:1,"new":1,
"catch":1,__METHOD__:1,"class":1,"case":1,exception:1,php_user_filter:1,"default":1,die:1,require:1,__FUNCTION__:1,enddeclare:1,"final":1,"try":1,"this":1,"switch":1,"continue":1,endfor:1,endif:1,declare:1,unset:1,"true":1,"false":1,namespace:1,trait:1,"goto":1,"instanceof":1,__DIR__:1,__NAMESPACE__:1,__halt_compiler:1},c:[hljs.CLCM,hljs.HCM,{cN:"comment",b:"/\\*",e:"\\*/",c:[{cN:"phpdoc",b:"\\s@[A-Za-z]+"}]},{cN:"comment",eB:!0,b:"__halt_compiler[^;]+;",e:"[\\n\\r]$"},hljs.CNM,hljs.BINARY_NUMBER_MODE,
hljs.inherit(hljs.ASM,{i:null}),hljs.inherit(hljs.QSM,{i:null}),{cN:"string",b:'b"',e:'"',c:[hljs.BE]},{cN:"string",b:"b'",e:"'",c:[hljs.BE]},{cN:"string",b:"<<<['\"]?\\w+['\"]?$",e:"^\\w+;",c:[hljs.BE]},{cN:"variable",b:"\\$+[a-zA-Z_\u007f-\u00ff][a-zA-Z0-9_\u007f-\u00ff]*"},{cN:"preprocessor",b:"<\\?php",r:10},{cN:"preprocessor",b:"\\?>"}]}};
hljs.LANGUAGES.python=function(){var b=[{cN:"string",b:"(u|b)?r?'''",e:"'''",r:10},{cN:"string",b:'(u|b)?r?"""',e:'"""',r:10},{cN:"string",b:"(u|r|ur)'",e:"'",c:[hljs.BE],r:10},{cN:"string",b:'(u|r|ur)"',e:'"',c:[hljs.BE],r:10},{cN:"string",b:"(b|br)'",e:"'",c:[hljs.BE]},{cN:"string",b:'(b|br)"',e:'"',c:[hljs.BE]}].concat([hljs.ASM,hljs.QSM]),e={cN:"title",b:hljs.UIR},d={cN:"params",b:"\\(",e:"\\)",c:b.concat([hljs.CNM])};return{dM:{k:{keyword:{and:1,elif:1,is:1,global:1,as:1,"in":1,"if":1,from:1,
raise:1,"for":1,except:1,"finally":1,print:1,"import":1,pass:1,"return":1,exec:1,"else":1,"break":1,not:1,"with":1,"class":1,assert:1,yield:1,"try":1,"while":1,"continue":1,del:1,or:1,def:1,lambda:1,nonlocal:10},built_in:{None:1,True:1,False:1,Ellipsis:1,NotImplemented:1}},i:"(</|->|\\?)",c:b.concat([hljs.HCM,{cN:"function",b:"\\bdef ",e:":",i:"$",k:{def:1},c:[e,d],r:10},{cN:"class",b:"\\bclass ",e:":",i:"[${]",k:{"class":1},c:[e,d],r:10},hljs.CNM,{cN:"decorator",b:"@",e:"$"}])}}}();
hljs.LANGUAGES.sql={cI:!0,dM:{i:"[^\\s]",c:[{cN:"operator",b:"(begin|start|commit|rollback|savepoint|lock|alter|create|drop|rename|call|delete|do|handler|insert|load|replace|select|truncate|update|set|show|pragma|grant)\\b",e:";|$",k:{keyword:{all:1,partial:1,global:1,month:1,current_timestamp:1,using:1,go:1,revoke:1,smallint:1,indicator:1,"end-exec":1,disconnect:1,zone:1,"with":1,character:1,assertion:1,to:1,add:1,current_user:1,usage:1,input:1,local:1,alter:1,match:1,collate:1,real:1,then:1,rollback:1,
get:1,read:1,timestamp:1,session_user:1,not:1,integer:1,bit:1,unique:1,day:1,minute:1,desc:1,insert:1,execute:1,like:1,ilike:2,level:1,decimal:1,drop:1,"continue":1,isolation:1,found:1,where:1,constraints:1,domain:1,right:1,national:1,some:1,module:1,transaction:1,relative:1,second:1,connect:1,escape:1,close:1,system_user:1,"for":1,deferred:1,section:1,cast:1,current:1,sqlstate:1,allocate:1,intersect:1,deallocate:1,numeric:1,"public":1,preserve:1,full:1,"goto":1,initially:1,asc:1,no:1,key:1,output:1,
collation:1,group:1,by:1,union:1,session:1,both:1,last:1,language:1,constraint:1,column:1,of:1,space:1,foreign:1,deferrable:1,prior:1,connection:1,unknown:1,action:1,commit:1,view:1,or:1,first:1,into:1,"float":1,year:1,primary:1,cascaded:1,except:1,restrict:1,set:1,references:1,names:1,table:1,outer:1,open:1,select:1,size:1,are:1,rows:1,from:1,prepare:1,distinct:1,leading:1,create:1,only:1,next:1,inner:1,authorization:1,schema:1,corresponding:1,option:1,declare:1,precision:1,immediate:1,"else":1,
timezone_minute:1,external:1,varying:1,translation:1,"true":1,"case":1,exception:1,join:1,hour:1,"default":1,"double":1,scroll:1,value:1,cursor:1,descriptor:1,values:1,dec:1,fetch:1,procedure:1,"delete":1,and:1,"false":1,"int":1,is:1,describe:1,"char":1,as:1,at:1,"in":1,varchar:1,"null":1,trailing:1,any:1,absolute:1,current_time:1,end:1,grant:1,privileges:1,when:1,cross:1,check:1,write:1,current_date:1,pad:1,begin:1,temporary:1,exec:1,time:1,update:1,catalog:1,user:1,sql:1,date:1,on:1,identity:1,
timezone_hour:1,natural:1,whenever:1,interval:1,work:1,order:1,cascade:1,diagnostics:1,nchar:1,having:1,left:1,call:1,"do":1,handler:1,load:1,replace:1,truncate:1,start:1,lock:1,show:1,pragma:1},aggregate:{count:1,sum:1,min:1,max:1,avg:1}},c:[{cN:"string",b:"'",e:"'",c:[hljs.BE,{b:"''"}],r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE,{b:'""'}],r:0},{cN:"string",b:"`",e:"`",c:[hljs.BE]},hljs.CNM,{b:"\\n"}]},hljs.CBLCLM,{cN:"comment",b:"--",e:"$"}]}};
hljs.LANGUAGES.ini={cI:!0,dM:{i:"[^\\s]",c:[{cN:"comment",b:";",e:"$"},{cN:"title",b:"^\\[",e:"\\]"},{cN:"setting",b:"^[a-z0-9_\\[\\]]+[ \\t]*=[ \\t]*",e:"$",c:[{cN:"value",eW:!0,k:{on:1,off:1,"true":1,"false":1,yes:1,no:1},c:[hljs.QSM,hljs.NM]}]}]}};
hljs.LANGUAGES.perl=function(){var b={getpwent:1,getservent:1,quotemeta:1,msgrcv:1,scalar:1,kill:1,dbmclose:1,undef:1,lc:1,ma:1,syswrite:1,tr:1,send:1,umask:1,sysopen:1,shmwrite:1,vec:1,qx:1,utime:1,local:1,oct:1,semctl:1,localtime:1,readpipe:1,"do":1,"return":1,format:1,read:1,sprintf:1,dbmopen:1,pop:1,getpgrp:1,not:1,getpwnam:1,rewinddir:1,qq:1,fileno:1,qw:1,endprotoent:1,wait:1,sethostent:1,bless:1,s:1,opendir:1,"continue":1,each:1,sleep:1,endgrent:1,shutdown:1,dump:1,chomp:1,connect:1,getsockname:1,
die:1,socketpair:1,close:1,flock:1,exists:1,index:1,shmget:1,sub:1,"for":1,endpwent:1,redo:1,lstat:1,msgctl:1,setpgrp:1,abs:1,exit:1,select:1,print:1,ref:1,gethostbyaddr:1,unshift:1,fcntl:1,syscall:1,"goto":1,getnetbyaddr:1,join:1,gmtime:1,symlink:1,semget:1,splice:1,x:1,getpeername:1,recv:1,log:1,setsockopt:1,cos:1,last:1,reverse:1,gethostbyname:1,getgrnam:1,study:1,formline:1,endhostent:1,times:1,chop:1,length:1,gethostent:1,getnetent:1,pack:1,getprotoent:1,getservbyname:1,rand:1,mkdir:1,pos:1,
chmod:1,y:1,substr:1,endnetent:1,printf:1,next:1,open:1,msgsnd:1,readdir:1,use:1,unlink:1,getsockopt:1,getpriority:1,rindex:1,wantarray:1,hex:1,system:1,getservbyport:1,endservent:1,"int":1,chr:1,untie:1,rmdir:1,prototype:1,tell:1,listen:1,fork:1,shmread:1,ucfirst:1,setprotoent:1,"else":1,sysseek:1,link:1,getgrgid:1,shmctl:1,waitpid:1,unpack:1,getnetbyname:1,reset:1,chdir:1,grep:1,split:1,require:1,caller:1,lcfirst:1,until:1,warn:1,"while":1,values:1,shift:1,telldir:1,getpwuid:1,my:1,getprotobynumber:1,
"delete":1,and:1,sort:1,uc:1,defined:1,srand:1,accept:1,"package":1,seekdir:1,getprotobyname:1,semop:1,our:1,rename:1,seek:1,"if":1,q:1,chroot:1,sysread:1,setpwent:1,no:1,crypt:1,getc:1,chown:1,sqrt:1,write:1,setnetent:1,setpriority:1,foreach:1,tie:1,sin:1,msgget:1,map:1,stat:1,getlogin:1,unless:1,elsif:1,truncate:1,exec:1,keys:1,glob:1,tied:1,closedir:1,ioctl:1,socket:1,readlink:1,eval:1,xor:1,readline:1,binmode:1,setservent:1,eof:1,ord:1,bind:1,alarm:1,pipe:1,atan2:1,getgrent:1,exp:1,time:1,push:1,
setgrent:1,gt:1,lt:1,or:1,ne:1,m:1},e={cN:"subst",b:"[$@]\\{",e:"\\}",k:b,r:10},d={cN:"variable",b:"\\$\\d"},h={cN:"variable",b:"[\\$\\%\\@\\*](\\^\\w\\b|#\\w+(\\:\\:\\w+)*|[^\\s\\w{]|{\\w+}|\\w+(\\:\\:\\w*)*)"},i=[hljs.BE,e,d,h],j={b:"->",c:[{b:hljs.IR},{b:"{",e:"}"}]},l={cN:"comment",b:"^(__END__|__DATA__)",e:"\\n$",r:5},d=[d,h,hljs.HCM,l,j,{cN:"string",b:"q[qwxr]?\\s*\\(",e:"\\)",c:i,r:5},{cN:"string",b:"q[qwxr]?\\s*\\[",e:"\\]",c:i,r:5},{cN:"string",b:"q[qwxr]?\\s*\\{",e:"\\}",c:i,r:5},{cN:"string",
b:"q[qwxr]?\\s*\\|",e:"\\|",c:i,r:5},{cN:"string",b:"q[qwxr]?\\s*\\<",e:"\\>",c:i,r:5},{cN:"string",b:"qw\\s+q",e:"q",c:i,r:5},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"string",b:'"',e:'"',c:i,r:0},{cN:"string",b:"`",e:"`",c:[hljs.BE]},{cN:"string",b:"{\\w+}",r:0},{cN:"string",b:"-?\\w+\\s*\\=\\>",r:0},{cN:"number",b:"(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b",r:0},{b:"("+hljs.RSR+"|split|return|print|reverse|grep)\\s*",k:{split:1,"return":1,print:1,reverse:1,
grep:1},r:0,c:[hljs.HCM,l,{cN:"regexp",b:"(s|tr|y)/(\\\\.|[^/])*/(\\\\.|[^/])*/[a-z]*",r:10},{cN:"regexp",b:"(m|qr)?/",e:"/[a-z]*",c:[hljs.BE],r:0}]},{cN:"sub",b:"\\bsub\\b",e:"(\\s*\\(.*?\\))?[;{]",k:{sub:1},r:5},{cN:"operator",b:"-\\w\\b",r:0},{cN:"pod",b:"\\=\\w",e:"\\=cut"}];e.c=d;j.c[1].c=d;return{dM:{k:b,c:d}}}();
hljs.LANGUAGES.objectivec=function(){return{dM:{k:{keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,sizeof:2,typedef:2,"const":1,struct:1,"for":1,union:1,unsigned:1,"long":1,"volatile":2,"static":1,"protected":1,bool:1,mutable:1,"if":1,"public":1,"do":1,"return":1,"goto":1,"void":2,"enum":1,"else":1,"break":1,extern:1,"true":1,"class":1,asm:1,"case":1,"short":1,"default":1,"double":1,"throw":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,
"continue":1,wchar_t:1,inline:1,readonly:1,assign:1,property:1,protocol:10,self:1,"synchronized":1,end:1,synthesize:50,id:1,optional:1,required:1,implementation:10,nonatomic:1,"interface":1,"super":1,unichar:1,"finally":2,dynamic:2,nil:1},built_in:{YES:5,NO:5,NULL:1,IBOutlet:50,IBAction:50,NSString:50,NSDictionary:50,CGRect:50,CGPoint:50,NSRange:50,release:1,retain:1,autorelease:50,UIButton:50,UILabel:50,UITextView:50,UIWebView:50,MKMapView:50,UISegmentedControl:50,NSObject:50,UITableViewDelegate:50,
UITableViewDataSource:50,NSThread:50,UIActivityIndicator:50,UITabbar:50,UIToolBar:50,UIBarButtonItem:50,UIImageView:50,NSAutoreleasePool:50,UITableView:50,BOOL:1,NSInteger:20,CGFloat:20,NSException:50,NSLog:50,NSMutableString:50,NSMutableArray:50,NSMutableDictionary:50,NSURL:50}},i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.CNM,hljs.QSM,{cN:"string",b:"'",e:"[^\\\\]'",i:"[^\\\\][^']"},{cN:"preprocessor",b:"#import",e:"$",c:[{cN:"title",b:'"',e:'"'},{cN:"title",b:"<",e:">"}]},{cN:"preprocessor",b:"#",e:"$"},
{cN:"class",b:"interface|class|protocol|implementation",e:"({|$)",k:{"interface":1,"class":1,protocol:5,implementation:5},c:[{cN:"id",b:hljs.UIR}]}]}}}();
hljs.LANGUAGES.coffeescript=function(){var b={keyword:{"in":1,"if":1,"for":1,"while":1,"finally":1,"new":1,"do":1,"return":1,"else":1,"break":1,"catch":1,"instanceof":1,"throw":1,"try":1,"this":1,"switch":1,"continue":1,"typeof":1,"delete":1,"debugger":1,"class":1,"extends":1,"super":1,then:1,unless:1,until:1,loop:2,of:2,by:1,when:2,and:1,or:1,is:1,isnt:2,not:1},literal:{"true":1,"false":1,"null":1,undefined:1,yes:1,no:1,on:1,off:1},reserved:{"case":1,"default":1,"function":1,"var":1,"void":1,"with":1,
"const":1,let:1,"enum":1,"export":1,"import":1,"native":1,__hasProp:1,__extends:1,__slice:1,__bind:1,__indexOf:1}},e={cN:"subst",b:"#\\{",e:"}",k:b,c:[hljs.CNM,hljs.BINARY_NUMBER_MODE]};return{dM:{k:b,c:[hljs.CNM,hljs.BINARY_NUMBER_MODE,hljs.ASM,{cN:"string",b:'"""',e:'"""',c:[hljs.BE,e]},{cN:"string",b:'"',e:'"',r:0,c:[hljs.BE,e]},{cN:"comment",b:"###",e:"###"},hljs.HCM,{cN:"regexp",b:"///",e:"///",c:[hljs.HCM]},{cN:"javascript",b:"`",e:"`",eB:!0,eE:!0,sL:"javascript"},{cN:"function",b:"[A-Za-z$_][0-9A-Za-z$_]*\\s*=\\s*(\\(.+\\))?\\s*[-=]>",
rB:!0,c:[{cN:"title",b:"[A-Za-z$_][0-9A-Za-z$_]*"},{cN:"params",b:"\\(",e:"\\)"}]}]}}}();
hljs.LANGUAGES.apache=function(){var b={cN:"number",b:"[\\$%]\\d+"};return{cI:!0,dM:{k:{keyword:{acceptfilter:1,acceptmutex:1,acceptpathinfo:1,accessfilename:1,action:1,addalt:1,addaltbyencoding:1,addaltbytype:1,addcharset:1,adddefaultcharset:1,adddescription:1,addencoding:1,addhandler:1,addicon:1,addiconbyencoding:1,addiconbytype:1,addinputfilter:1,addlanguage:1,addmoduleinfo:1,addoutputfilter:1,addoutputfilterbytype:1,addtype:1,alias:1,aliasmatch:1,allow:1,allowconnect:1,allowencodedslashes:1,allowoverride:1,
anonymous:1,anonymous_logemail:1,anonymous_mustgiveemail:1,anonymous_nouserid:1,anonymous_verifyemail:1,authbasicauthoritative:1,authbasicprovider:1,authdbduserpwquery:1,authdbduserrealmquery:1,authdbmgroupfile:1,authdbmtype:1,authdbmuserfile:1,authdefaultauthoritative:1,authdigestalgorithm:1,authdigestdomain:1,authdigestnccheck:1,authdigestnonceformat:1,authdigestnoncelifetime:1,authdigestprovider:1,authdigestqop:1,authdigestshmemsize:1,authgroupfile:1,authldapbinddn:1,authldapbindpassword:1,authldapcharsetconfig:1,
authldapcomparednonserver:1,authldapdereferencealiases:1,authldapgroupattribute:1,authldapgroupattributeisdn:1,authldapremoteuserattribute:1,authldapremoteuserisdn:1,authldapurl:1,authname:1,authnprovideralias:1,authtype:1,authuserfile:1,authzdbmauthoritative:1,authzdbmtype:1,authzdefaultauthoritative:1,authzgroupfileauthoritative:1,authzldapauthoritative:1,authzownerauthoritative:1,authzuserauthoritative:1,balancermember:1,browsermatch:1,browsermatchnocase:1,bufferedlogs:1,cachedefaultexpire:1,cachedirlength:1,
cachedirlevels:1,cachedisable:1,cacheenable:1,cachefile:1,cacheignorecachecontrol:1,cacheignoreheaders:1,cacheignorenolastmod:1,cacheignorequerystring:1,cachelastmodifiedfactor:1,cachemaxexpire:1,cachemaxfilesize:1,cacheminfilesize:1,cachenegotiateddocs:1,cacheroot:1,cachestorenostore:1,cachestoreprivate:1,cgimapextension:1,charsetdefault:1,charsetoptions:1,charsetsourceenc:1,checkcaseonly:1,checkspelling:1,chrootdir:1,contentdigest:1,cookiedomain:1,cookieexpires:1,cookielog:1,cookiename:1,cookiestyle:1,
cookietracking:1,coredumpdirectory:1,customlog:1,dav:1,davdepthinfinity:1,davgenericlockdb:1,davlockdb:1,davmintimeout:1,dbdexptime:1,dbdkeep:1,dbdmax:1,dbdmin:1,dbdparams:1,dbdpersist:1,dbdpreparesql:1,dbdriver:1,defaulticon:1,defaultlanguage:1,defaulttype:1,deflatebuffersize:1,deflatecompressionlevel:1,deflatefilternote:1,deflatememlevel:1,deflatewindowsize:1,deny:1,directoryindex:1,directorymatch:1,directoryslash:1,documentroot:1,dumpioinput:1,dumpiologlevel:1,dumpiooutput:1,enableexceptionhook:1,
enablemmap:1,enablesendfile:1,errordocument:1,errorlog:1,example:1,expiresactive:1,expiresbytype:1,expiresdefault:1,extendedstatus:1,extfilterdefine:1,extfilteroptions:1,fileetag:1,filterchain:1,filterdeclare:1,filterprotocol:1,filterprovider:1,filtertrace:1,forcelanguagepriority:1,forcetype:1,forensiclog:1,gracefulshutdowntimeout:1,group:1,header:1,headername:1,hostnamelookups:1,identitycheck:1,identitychecktimeout:1,imapbase:1,imapdefault:1,imapmenu:1,include:1,indexheadinsert:1,indexignore:1,indexoptions:1,
indexorderdefault:1,indexstylesheet:1,isapiappendlogtoerrors:1,isapiappendlogtoquery:1,isapicachefile:1,isapifakeasync:1,isapilognotsupported:1,isapireadaheadbuffer:1,keepalive:1,keepalivetimeout:1,languagepriority:1,ldapcacheentries:1,ldapcachettl:1,ldapconnectiontimeout:1,ldapopcacheentries:1,ldapopcachettl:1,ldapsharedcachefile:1,ldapsharedcachesize:1,ldaptrustedclientcert:1,ldaptrustedglobalcert:1,ldaptrustedmode:1,ldapverifyservercert:1,limitinternalrecursion:1,limitrequestbody:1,limitrequestfields:1,
limitrequestfieldsize:1,limitrequestline:1,limitxmlrequestbody:1,listen:1,listenbacklog:1,loadfile:1,loadmodule:1,lockfile:1,logformat:1,loglevel:1,maxclients:1,maxkeepaliverequests:1,maxmemfree:1,maxrequestsperchild:1,maxrequestsperthread:1,maxspareservers:1,maxsparethreads:1,maxthreads:1,mcachemaxobjectcount:1,mcachemaxobjectsize:1,mcachemaxstreamingbuffer:1,mcacheminobjectsize:1,mcacheremovalalgorithm:1,mcachesize:1,metadir:1,metafiles:1,metasuffix:1,mimemagicfile:1,minspareservers:1,minsparethreads:1,
mmapfile:1,mod_gzip_on:1,mod_gzip_add_header_count:1,mod_gzip_keep_workfiles:1,mod_gzip_dechunk:1,mod_gzip_min_http:1,mod_gzip_minimum_file_size:1,mod_gzip_maximum_file_size:1,mod_gzip_maximum_inmem_size:1,mod_gzip_temp_dir:1,mod_gzip_item_include:1,mod_gzip_item_exclude:1,mod_gzip_command_version:1,mod_gzip_can_negotiate:1,mod_gzip_handle_methods:1,mod_gzip_static_suffix:1,mod_gzip_send_vary:1,mod_gzip_update_static:1,modmimeusepathinfo:1,multiviewsmatch:1,namevirtualhost:1,noproxy:1,nwssltrustedcerts:1,
nwsslupgradeable:1,options:1,order:1,passenv:1,pidfile:1,protocolecho:1,proxybadheader:1,proxyblock:1,proxydomain:1,proxyerroroverride:1,proxyftpdircharset:1,proxyiobuffersize:1,proxymaxforwards:1,proxypass:1,proxypassinterpolateenv:1,proxypassmatch:1,proxypassreverse:1,proxypassreversecookiedomain:1,proxypassreversecookiepath:1,proxypreservehost:1,proxyreceivebuffersize:1,proxyremote:1,proxyremotematch:1,proxyrequests:1,proxyset:1,proxystatus:1,proxytimeout:1,proxyvia:1,readmename:1,receivebuffersize:1,
redirect:1,redirectmatch:1,redirectpermanent:1,redirecttemp:1,removecharset:1,removeencoding:1,removehandler:1,removeinputfilter:1,removelanguage:1,removeoutputfilter:1,removetype:1,requestheader:1,require:2,rewritebase:1,rewritecond:10,rewriteengine:1,rewritelock:1,rewritelog:1,rewriteloglevel:1,rewritemap:1,rewriteoptions:1,rewriterule:10,rlimitcpu:1,rlimitmem:1,rlimitnproc:1,satisfy:1,scoreboardfile:1,script:1,scriptalias:1,scriptaliasmatch:1,scriptinterpretersource:1,scriptlog:1,scriptlogbuffer:1,
scriptloglength:1,scriptsock:1,securelisten:1,seerequesttail:1,sendbuffersize:1,serveradmin:1,serveralias:1,serverlimit:1,servername:1,serverpath:1,serverroot:1,serversignature:1,servertokens:1,setenv:1,setenvif:1,setenvifnocase:1,sethandler:1,setinputfilter:1,setoutputfilter:1,ssienableaccess:1,ssiendtag:1,ssierrormsg:1,ssistarttag:1,ssitimeformat:1,ssiundefinedecho:1,sslcacertificatefile:1,sslcacertificatepath:1,sslcadnrequestfile:1,sslcadnrequestpath:1,sslcarevocationfile:1,sslcarevocationpath:1,
sslcertificatechainfile:1,sslcertificatefile:1,sslcertificatekeyfile:1,sslciphersuite:1,sslcryptodevice:1,sslengine:1,sslhonorciperorder:1,sslmutex:1,ssloptions:1,sslpassphrasedialog:1,sslprotocol:1,sslproxycacertificatefile:1,sslproxycacertificatepath:1,sslproxycarevocationfile:1,sslproxycarevocationpath:1,sslproxyciphersuite:1,sslproxyengine:1,sslproxymachinecertificatefile:1,sslproxymachinecertificatepath:1,sslproxyprotocol:1,sslproxyverify:1,sslproxyverifydepth:1,sslrandomseed:1,sslrequire:1,
sslrequiressl:1,sslsessioncache:1,sslsessioncachetimeout:1,sslusername:1,sslverifyclient:1,sslverifydepth:1,startservers:1,startthreads:1,substitute:1,suexecusergroup:1,threadlimit:1,threadsperchild:1,threadstacksize:1,timeout:1,traceenable:1,transferlog:1,typesconfig:1,unsetenv:1,usecanonicalname:1,usecanonicalphysicalport:1,user:1,userdir:1,virtualdocumentroot:1,virtualdocumentrootip:1,virtualscriptalias:1,virtualscriptaliasip:1,win32disableacceptex:1,xbithack:1},literal:{on:1,off:1}},c:[hljs.HCM,
{cN:"sqbracket",b:"\\s\\[",e:"\\]$"},{cN:"cbracket",b:"[\\$%]\\{",e:"\\}",c:["self",b]},b,{cN:"tag",b:"</?",e:">"},hljs.QSM]}}}();
hljs.LANGUAGES.cpp=function(){var b={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,
typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,
unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:b,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:b,r:10,c:["self"]}]}}}();
