var Showdown={extensions:{}},forEach=Showdown.forEach=function(b,g){if("function"==typeof b.forEach)b.forEach(g);else{var f,d=b.length;for(f=0;f<d;f++)g(b[f],f,b)}},stdExtName=function(b){return b.replace(/[_-]||\s/g,"").toLowerCase()};
Showdown.converter=function(b){var g,f,d,i=0,l=[],p=[];if("undefind"!=typeof module&&"undefined"!=typeof exports&&"undefind"!=typeof require){var u=require("fs");u&&(u=u.readdirSync((__dirname||".")+"/extensions").filter(function(a){return~a.indexOf(".js")}).map(function(a){return a.replace(/\.js$/,"")}),Showdown.forEach(u,function(a){var c=stdExtName(a);Showdown.extensions[c]=require("./extensions/"+a)}))}this.makeHtml=function(a){g={};f={};d=[];a=a.replace(/~/g,"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,
"\n");a=a.replace(/\r/g,"\n");a="\n\n"+a+"\n\n";a=A(a);a=a.replace(/^[ \t]+$/mg,"");Showdown.forEach(l,function(c){a=r(c,a)});var c=a,a=(c+="~0",c=c.replace(/(?:^|\n)```(.*)\n([\s\S]*?)\n```/g,function(a,c,b){a=b;return a=K(a),a=A(a),a=a.replace(/^\n+/g,""),a=a.replace(/\n+$/g,""),a="<pre><code"+(c?' class="'+c+'"':"")+">"+a+"\n</code></pre>",z(a)}),c=c.replace(/~0/,""),c),c=a=x(a);return a=(c+="~0",c=c.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|(?=~0))/gm,
function(a,c,b,e,h){return c=c.toLowerCase(),g[c]=s(b),e?e+h:(h&&(f[c]=h.replace(/"/g,"&quot;")),"")}),c=c.replace(/~0/,""),c),a=y(a),a=O(a),a=a.replace(/~D/g,"$$"),a=a.replace(/~T/g,"~"),Showdown.forEach(p,function(c){a=r(c,a)}),a};if(b&&b.extensions){var m=this;Showdown.forEach(b.extensions,function(a){"string"==typeof a&&(a=Showdown.extensions[stdExtName(a)]);if("function"!=typeof a)throw"Extension '"+a+"' could not be loaded.  It was either not found or is not a valid extension.";Showdown.forEach(a(m),
function(a){a.type?"language"===a.type||"lang"===a.type?l.push(a):("output"===a.type||"html"===a.type)&&p.push(a):p.push(a)})})}var r=function(a,c){if(a.regex)return c.replace(RegExp(a.regex,"g"),a.replace);if(a.filter)return a.filter(c)},x=function(a){a=a.replace(/\n/g,"\n\n");return a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,h),a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|style|section|header|footer|nav|article|aside)\b[^\r]*?<\/\2>[ \t]*(?=\n+)\n)/gm,
h),a=a.replace(/(\n[ ]{0,3}(<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,h),a=a.replace(/(\n\n[ ]{0,3}<!(--[^\r]*?--\s*)+>[ \t]*(?=\n{2,}))/g,h),a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,h),a=a.replace(/\n\n/g,"\n"),a},h=function(a,c){var b=c;return b=b.replace(/\n\n/g,"\n"),b=b.replace(/^\n/,""),b=b.replace(/\n+$/g,""),b="\n\n~K"+(d.push(b)-1)+"K\n\n",b},y=function(a){for(var c=a,b=function(a){return a.replace(/[^\w]/g,"").toLowerCase()},a=(c=c.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,
function(a,c){return z('<h1 id="'+b(c)+'">'+e(c)+"</h1>")}),c=c.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(a,c){return z('<h2 id="'+b(c)+'">'+e(c)+"</h2>")}),c=c.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,function(a,c,h){a=c.length;return z("<h"+a+' id="'+b(h)+'">'+e(h)+"</h"+a+">")}),c),c=z("<hr />"),a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,c),a=a.replace(/^[ ]{0,2}([ ]?\-[ ]?){3,}[ \t]*$/gm,c),a=a.replace(/^[ ]{0,2}([ ]?\_[ ]?){3,}[ \t]*$/gm,c),c=a=q(a),c=a=(c+="~0",c=c.replace(/(?:\n\n|^)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,
function(a,c,b){a=c;return a=K(v(a)),a=A(a),a=a.replace(/^\n+/g,""),a=a.replace(/\n+$/g,""),a="<pre><code>"+a+"\n</code></pre>",z(a)+b}),c=c.replace(/~0/,""),c),a=(c=c.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,c){var b=c;return b=b.replace(/^[ \t]*>[ \t]?/gm,"~0"),b=b.replace(/~0/g,""),b=b.replace(/^[ \t]+$/gm,""),b=y(b),b=b.replace(/(^|\n)/g,"$1  "),b=b.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,c){var b=c;return b=b.replace(/^  /mg,"~0"),b=b.replace(/~0/g,""),b}),z("<blockquote>\n"+
b+"\n</blockquote>")}),c),a=x(a),c=a.replace(/^\n+/g,""),c=c.replace(/\n+$/g,""),h=c.split(/\n{2,}/g),c=[],n=h.length,k=0;k<n;k++){var f=h[k];0<=f.search(/~K(\d+)K/g)?c.push(f):0<=f.search(/\S/)&&(f=e(f),f=f.replace(/^([ \t]*)/g,"<p>"),f+="</p>",c.push(f))}n=c.length;for(k=0;k<n;k++)for(;0<=c[k].search(/~K(\d+)K/);)h=d[RegExp.$1],h=h.replace(/\$/g,"$$$$"),c[k]=c[k].replace(/~K\d+K/,h);return a=c.join("\n\n"),a},e=function(a){var c=a,c=a=(c=c.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(a,
c,b,e){a=e;return a=a.replace(/^([ \t]*)/g,""),a=a.replace(/[ \t]*$/g,""),a=K(a),c+"<code>"+a+"</code>"}),c),c=a=(c=c.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--.*?--\s*)+>)/gi,function(a){a=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return a=t(a,"\\`*_"),a}),c),c=a=(c=c.replace(/\\(\\)/g,B),c=c.replace(/\\([`*_{}\[\]()>#+-.!])/g,B),c),c=a=(c=c.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,n),c=c.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,n),c),c=a=
(c=c.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,k),c=c.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?(.*?(?:\(.*?\).*?)?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,k),c=c.replace(/(\[([^\[\]]+)\])()()()()()/g,k),c),a=(c=c.replace(/<((https?|ftp|dict):[^'">\s]+)>/gi,'<a href="$1">$1</a>'),c=c.replace(/<(?:mailto:)?([-.\w]+\@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)>/gi,function(a,c){var b=O(c),e=[function(a){return"&#"+a.charCodeAt(0)+";"},function(a){return"&#x"+a.charCodeAt(0).toString(16)+
";"},function(a){return a}];return b="mailto:"+b,b=b.replace(/./g,function(a){if("@"==a)a=e[Math.floor(2*Math.random())](a);else if(":"!=a)var c=Math.random(),a=0.9<c?e[2](a):0.45<c?e[1](a):e[0](a);return a}),b='<a href="'+b+'">'+b+"</a>",b=b.replace(/">.+:/g,'">'),b}),c),c=a=s(a);return a=(c=c.replace(/(\*\*|__)(?=\S)([^\r]*?\S[*_]*)\1/g,"<strong>$2</strong>"),c=c.replace(/(\*|_)(?=\S)([^\r]*?\S)\1/g,"<em>$2</em>"),c),a=a.replace(/  +\n/g," <br />\n"),a},k=function(a,c,b,e,h,k,n,d){void 0==d&&(d=
"");a=e.toLowerCase();if(""==h)if(""==a&&(a=b.toLowerCase().replace(/ ?\n/g," ")),void 0!=g[a])h=g[a],void 0!=f[a]&&(d=f[a]);else{if(!(-1<c.search(/\(\s*\)$/m)))return c;h=""}h=t(h,"*_");c='<a href="'+h+'"';return""!=d&&(d=d.replace(/"/g,"&quot;"),d=t(d,"*_"),c+=' title="'+d+'"'),c+=">"+b+"</a>",c},n=function(a,c,b,e,h,k,n,d){a=b;e=e.toLowerCase();d||(d="");if(""==h){""==e&&(e=a.toLowerCase().replace(/ ?\n/g," "));if(void 0==g[e])return c;h=g[e];void 0!=f[e]&&(d=f[e])}a=a.replace(/"/g,"&quot;");h=
t(h,"*_");c='<img src="'+h+'" alt="'+a+'"';return d=d.replace(/"/g,"&quot;"),d=t(d,"*_"),c+=' title="'+d+'"',c+=" />",c},j,q=function(a){var a=a+"~0",c=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;return i?a=a.replace(c,function(a,c,b){a=c;b=-1<b.search(/[*+-]/g)?"ul":"ol";a=a.replace(/\n{2,}/g,"\n\n\n");a=j(a);return a=a.replace(/\s+$/,""),a="<"+b+">"+a+"</"+b+">\n",a}):(c=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g,
a=a.replace(c,function(a,c,b,e){a=b;e=-1<e.search(/[*+-]/g)?"ul":"ol";a=a.replace(/\n{2,}/g,"\n\n\n");a=j(a);return a=c+"<"+e+">\n"+a+"</"+e+">\n",a})),a=a.replace(/~0/,""),a};j=function(a){return i++,a=a.replace(/\n{2,}$/,"\n"),a+="~0",a=a.replace(/(\n)?(^[ \t]*)([*+-]|\d+[.])[ \t]+([^\r]+?(\n{1,2}))(?=\n*(~0|\2([*+-]|\d+[.])[ \t]+))/gm,function(a,b,h,d,k){a=k;return b||-1<a.search(/\n{2,}/)?a=y(v(a)):(a=q(v(a)),a=a.replace(/\n$/,""),a=e(a)),"<li>"+a+"</li>\n"}),a=a.replace(/~0/g,""),i--,a};var z=
function(a){return a=a.replace(/(^\n+|\n+$)/g,""),"\n\n~K"+(d.push(a)-1)+"K\n\n"},K=function(a){return a=a.replace(/&/g,"&amp;"),a=a.replace(/</g,"&lt;"),a=a.replace(/>/g,"&gt;"),a=t(a,"*_{}[]\\",!1),a},s=function(a){return a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;"),a=a.replace(/<(?![a-z\/?\$!])/gi,"&lt;"),a},O=function(a){return a=a.replace(/~E(\d+)E/g,function(a,b){var e=parseInt(b);return String.fromCharCode(e)}),a},v=function(a){return a=a.replace(/^(\t|[ ]{1,4})/gm,"~0"),a=a.replace(/~0/g,
""),a},A=function(a){return a=a.replace(/\t(?=\t)/g,"    "),a=a.replace(/\t/g,"~A~B"),a=a.replace(/~B(.+?)~A/g,function(a,b){for(var e=b,h=4-e.length%4,k=0;k<h;k++)e+=" ";return e}),a=a.replace(/~A/g,"    "),a=a.replace(/~B/g,""),a},t=function(a,b,e){b="(["+b.replace(/([\[\]\\])/g,"\\$1")+"])";e&&(b="\\\\"+b);return a=a.replace(RegExp(b,"g"),B),a},B=function(a,b){return"~E"+b.charCodeAt(0)+"E"}};"undefined"!=typeof module&&(module.exports=Showdown);
"function"==typeof define&&define.amd&&define("showdown",function(){return Showdown});(function(b){function g(f){if("string"===typeof f.data){var d=f.handler,g=f.data.toLowerCase().split(" ");f.handler=function(f){if(!(this!==f.target&&(/textarea|select/i.test(f.target.nodeName)||"text"===f.target.type))){var p="keypress"!==f.type&&b.hotkeys.specialKeys[f.which],u=String.fromCharCode(f.which).toLowerCase(),m="",r={};f.altKey&&"alt"!==p&&(m+="alt+");f.ctrlKey&&"ctrl"!==p&&(m+="ctrl+");f.metaKey&&(!f.ctrlKey&&"meta"!==p)&&(m+="meta+");f.shiftKey&&"shift"!==p&&(m+="shift+");p?r[m+p]=
!0:(r[m+u]=!0,r[m+b.hotkeys.shiftNums[u]]=!0,"shift+"===m&&(r[b.hotkeys.shiftNums[u]]=!0));p=0;for(u=g.length;p<u;p++)if(r[g[p]])return d.apply(this,arguments)}}}}b.hotkeys={version:"0.8",specialKeys:{8:"backspace",9:"tab",13:"return",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"capslock",27:"esc",32:"space",33:"pageup",34:"pagedown",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"del",96:"0",97:"1",98:"2",99:"3",100:"4",101:"5",102:"6",103:"7",104:"8",105:"9",106:"*",107:"+",
109:"-",110:".",111:"/",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",144:"numlock",145:"scroll",191:"/",224:"meta"},shiftNums:{"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(","0":")","-":"_","=":"+",";":": ","'":'"',",":"<",".":">","/":"?","\\":"|"}};b.each(["keydown","keyup","keypress"],function(){b.event.special[this]={add:g}})})(jQuery);var relativeDate=function(b){var g=[[42E3,"just now"],[9E4,"a minute ago"],[36E5,"minutes ago",6E4],[54E5,"an hour ago"],[864E5,"hours ago",36E5],[1728E5,"yesterday"],[6048E5,"days ago",864E5],[9072E5,"a week ago"],[2628E6,"weeks ago",6048E5],[3942E6,"a month ago"],[31536E6,"months ago",2628E6],[47304E6,"a year ago"],[Number.MAX_VALUE,"years ago",31536E6]];return function(f,d){!d&&(d=(new Date).getTime());d instanceof Date&&(d=d.getTime());f instanceof Date&&(f=f.getTime());var i=d-f,l,p,u;p=-1;for(u=
g.length;++p<u;)if(l=g[p],i<l[0])return l[2]==b?l[1]:Math.round(i/l[2])+" "+l[1]}}();"undefined"!=typeof module&&module.exports&&(module.exports=relativeDate);function engine(b){var g=new Showdown.converter;!b.type&&b.src&&(b.src.match(".md$")?b.type="markdown":b.src.match(".html$")?b.type="html":b.src.match("rss|atom$")?b.type="rss":b.src.match(/manifest\.json$/)&&(b.type="blog"));if(!b.src)return console.log("src required",b);if(b.target)b.target=$(b.target);else return console.log("target DOM element required",b);this.target=b.target;var f=[],d=!1,i=!1,l={};l.rss=l.atom=function(b,f){$.ajax({url:"https://ajax.googleapis.com/ajax/services/feed/load",
data:{v:"1.0",q:b,num:-1},type:"GET",dataType:"jsonp",error:function(b,d){f(d)},success:function(b){if(b.responseDetails)return console.log(b.responseDetails);var b=b.responseData.feed.entries,d=[],h;for(h in b)d[h]={title:b[h].title,url:b[h].url,html:b[h].content,date:b[h].publishedDate,author:b[h].author,type:"blog"};f(d)}})};l.blog=function(b,f){$.ajax({url:b,success:function(d){var g=b.replace(/[^\/]*$/,""),h=[],y;for(y in d)d[y].src=g+d[y].src,h[y]=function(b){return function(h){l.markdown(b,
function(f){f[0].type="blog";f[0].title||(f[0].title=b.match(/([^\/]+)\.[^.]+$/)[1]);h(f[0])})}}(d[y].src);f(h)},error:function(b,d){f(d)},dataType:"json"})};l.raw=l.html=function(b,f){$.ajax({url:b,dataType:"html",error:function(b,d){f(d)},success:function(b){f([{html:b}])}})};l.markdown=function(b,f){l.raw(b,function(b){b[0].html=g.makeHtml(b[0].html);f(b)})};var p=this.render=function(){if(f.length){d=!0;var g=$("<section />").appendTo(b.target),l=f.shift();if("object"==typeof l)var i=l,l=function(b){b(i)};
else g.html('<div class="throbber"></div>');l(function(b){g.html(b.html).addClass(b.type);var h=$("<h1 />").prependTo(g).text(b.title);b.title&&g.append("<hr />");b.date&&$("<time />").attr("datetime",b.date).text(relativeDate(new Date(b.date))).appendTo(h);b.author&&$("<span />").addClass("note").text(" by ").append(b.author).appendTo(h);$("pre code",g).each(function(b,e){hljs.highlightBlock(e)});d=!1})}};this.evaluate=function(){!d&&i&&$("section:visible",b.target).length&&0!=f.length&&$(window).scrollTop()>
$("section",b.target).last().offset().top-$(window).height()&&p()};$(window).scroll(this.evaluate);setInterval(function(){$("time[datetime]",b.target).each(function(){var b=new Date($(this).attr("datetime"));$(this).text(relativeDate(b))})},3E4);l[b.type](b.src,function(b){f=b;p();i=!0})};$(function(){generateNav();animations();hotkeys()});
function generateNav(){$("nav").empty();$("article[data-name]").each(function(b,g){var g=$(g),f="#"+g.data("name").replace(/[^0-9a-z]+/gi,"-"),d=$("<a />").addClass("service");d.text(g.data("name"));d.appendTo("nav");d.click(showThisArticle);d.one("mouseenter",function(){initArticle(g)});d.data("article",g);d.attr("href",f);d.attr("title",g.data("hint"));document.location.hash==f&&d.each(showThisArticle);g.hasClass("default")&&1>=document.location.hash.length&&d.each(showThisArticle)})}
function showThisArticle(){var b=$(this).data("article");$("article").hide();b.show().text();$("nav .service").removeClass("active");$(this).addClass("active");if(!b.hasClass("default")||document.location.hash)document.location.hash=$(this).attr("href");$(".articles header").html(b.data("hint"));initArticle(b)}function preloadArticles(){$("article[data-preload]").each(function(){initArticle($(this))})}
function initArticle(b){if(b.data("engine")||!b.data("src"))return!1;b.data("engine",new engine({src:b.data("src"),target:b,type:b.data("type")}))}
function animations(){$("#backdrop > img").hide().bind("load",function(){$(this).fadeIn(3500);preloadArticles()});$("article .logos img").css("opacity",0).load(function(){$(this).fadeTo("fast",0.7)});$("#contact").hide();var b=function(){$("#logo .quote").stop().fadeOut();$("#logo h1").stop().animate({"margin-top":"50px"})};setTimeout(function(){b();$("#logo").bind("mouseleave",b)},4E3);$("#logo").bind("mouseenter",function(){$("#logo .quote").stop().fadeIn();$("#logo h1").stop().animate({"margin-top":"26px"})});
var g=setTimeout(function(){$("#contact").hide().fadeIn()},6E3);$(window).one("scroll",function(){clearTimeout(g);$("#contact").fadeIn()});$.browser.msie&&9<=parseInt($.browser.version)&&setTimeout(function(){$("img").trigger("load")},3E3)}
function hotkeys(){$(document).bind("keydown","right",function(){($(".service").hasClass("active")?$(".active").next():$(".service").first()).each(showThisArticle)});$(document).bind("keydown","left",function(){($(".service").hasClass("active")?$(".active").prev():$(".service").first()).each(showThisArticle)});$(document).bind("keyup","return",function(){$("nav a.active").each(function(){$(".active").css("top",0)})}).bind("keydown","return",function(){$(".active").css("position","relative").css("top",
"2px")})};var hljs=new function(){function b(b){return b.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function g(b,f,e){return RegExp(f,"m"+(b.cI?"i":"")+(e?"g":""))}function f(b,d){for(var e="",k=0;k<b.childNodes.length;k++)if(3==b.childNodes[k].nodeType){var g=b.childNodes[k].nodeValue;d&&(g=g.replace(/\n/g,""));e+=g}else e="BR"==b.childNodes[k].nodeName?e+"\n":e+f(b.childNodes[k]);/MSIE [678]/.test(navigator.userAgent)&&(e=e.replace(/\r/g,"\n"));return e}function d(b){var f=[];(function(b,d){for(var h=0;h<
b.childNodes.length;h++)3==b.childNodes[h].nodeType?d+=b.childNodes[h].nodeValue.length:"BR"==b.childNodes[h].nodeName?d+=1:1==b.childNodes[h].nodeType&&(f.push({event:"start",offset:d,node:b.childNodes[h]}),d=arguments.callee(b.childNodes[h],d),f.push({event:"stop",offset:d,node:b.childNodes[h]}));return d})(b,0);return f}function i(){function b(e,f,d){if(!e.compiled){d||(e.bR=g(f,e.b?e.b:"\\B|\\b"),!e.e&&!e.eW&&(e.e="\\B|\\b"),e.e&&(e.eR=g(f,e.e)));e.i&&(e.iR=g(f,e.i));void 0===e.r&&(e.r=1);if(e.k){e.lR=
g(f,e.l||hljs.IR,!0);for(var j in e.k)if(e.k.hasOwnProperty(j)){e.k[j]instanceof Object?d=e.k[j]:(d=e.k,j="keyword");for(var y in d)d.hasOwnProperty(y)&&(e.k[y]=[j,d[y]])}}e.c||(e.c=[]);e.compiled=!0;for(j=0;j<e.c.length;j++)"self"==e.c[j]&&(e.c[j]=e),b(e.c[j],f,!1);e.starts&&b(e.starts,f,!1)}}for(var f in x)x.hasOwnProperty(f)&&b(x[f].dM,x[f],!0)}function l(f,d){function e(a,b){if(q[a].e&&q[a].eR.test(b))return 1;if(q[a].eW){var c=e(a-1,b);return c?c+1:0}return 0}function k(a,c){if(c.sL&&x[c.sL]){var e=
l(c.sL,a);p+=e.keyword_count;return e.value}e=b(a);if(c.k){var f="",d=0;c.lR.lastIndex=0;for(var h=c.lR.exec(e);h;){var f=f+e.substr(d,h.index-d),d=c,g=h,g=j.cI?g[0].toLowerCase():g[0];(d=(d=d.k[g])&&d instanceof Array?d:!1)?(p+=d[1],f+='<span class="'+d[0]+'">'+h[0]+"</span>"):f+=h[0];d=c.lR.lastIndex;h=c.lR.exec(e)}e=f+e.substr(d,e.length-d)}return e}function n(a,c){var e=a.cN?'<span class="'+a.cN+'">':"";a.rB?(s+=e,a.buffer=""):a.eB?(s+=b(c)+e,a.buffer=""):(s+=e,a.buffer=c);q.push(a);z+=a.r}i.called||
(i(),i.called=!0);var j=x[f],q=[j.dM],z=0,p=0,s="";try{var m,v=0;j.dM.buffer="";do{var u=d,t=v,r=q[q.length-1];if(!r.t){for(var a=r,c,H=r,R=j,I=[],L=0;L<H.c.length;L++)I.push(H.c[L].b);var J=q.length-1;do q[J].e&&I.push(q[J].e),J--;while(q[J+1].eW);H.i&&I.push(H.i);c=g(R,"("+I.join("|")+")",!0);a.t=c}r.t.lastIndex=t;var M=r.t.exec(u);m=M?[u.substr(t,M.index-t),M[0],!1]:[u.substr(t),"",!0];var D;var E=m[0],C=m[1],w=q[q.length-1];if(m[2])s+=k(w.buffer+E,w),D=!1;else{var F;b:{u=C;t=w;for(a=0;a<t.c.length;a++)if(t.c[a].bR.test(u)){F=
t.c[a];break b}F=void 0}if(F)s+=k(w.buffer+E,w),n(F,C),D=F.rB;else{var N=e(q.length-1,C);if(N){for(var G=w.cN?"</span>":"",s=w.rE?s+(k(w.buffer+E,w)+G):w.eE?s+(k(w.buffer+E,w)+G+b(C)):s+(k(w.buffer+E+C,w)+G);1<N;)G=q[q.length-2].cN?"</span>":"",s+=G,N--,q.length--;var P=q[q.length-1];q.length--;q[q.length-1].buffer="";P.starts&&n(P.starts,"");D=w.rE}else{if(w.i&&w.iR.test(C))throw"Illegal";D=void 0}}}v+=m[0].length;D||(v+=m[1].length)}while(!m[2]);if(1<q.length)throw"Illegal";return{r:z,keyword_count:p,
value:s}}catch(Q){if("Illegal"==Q)return{r:0,keyword_count:0,value:b(d)};throw Q;}}function p(f){var d={keyword_count:0,r:0,value:b(f)},e=d,g;for(g in x)if(x.hasOwnProperty(g)){var n=l(g,f);n.language=g;n.keyword_count+n.r>e.keyword_count+e.r&&(e=n);n.keyword_count+n.r>d.keyword_count+d.r&&(e=d,d=n)}e.language&&(d.second_best=e);return d}function u(b,d,e){d&&(b=b.replace(/^((<[^>]+>|\t)+)/gm,function(b,e){return e.replace(/\t/g,d)}));e&&(b=b.replace(/\n/g,"<br>"));return b}function m(h,g,e){var k=
f(h,e),n;a:{var j=h;n=j.className.split(/\s+/);n=n.concat(j.parentNode.className.split(/\s+/));for(j=0;j<n.length;j++){var q=n[j].replace(/^language-/,"");if(x[q]||"no-highlight"==q){n=q;break a}}n=void 0}var i;if("no-highlight"!=n){n?j=l(n,k):(j=p(k),n=j.language);var m=d(h);if(m.length){i=document.createElement("pre");i.innerHTML=j.value;q=j;i=d(i);for(var s=function(a){for(var e="<"+a.nodeName.toLowerCase(),d=0;d<a.attributes.length;d++){var f=a.attributes[d],e=e+(" "+f.nodeName.toLowerCase());
void 0!==f.value&&(!1!==f.value&&null!==f.value)&&(e+='="'+b(f.value)+'"')}return e+">"},r=0,v="",A=[];m.length||i.length;){var t=(m.length&&i.length?m[0].offset!=i[0].offset?m[0].offset<i[0].offset?m:i:"start"==i[0].event?m:i:m.length?m:i).splice(0,1)[0],v=v+b(k.substr(r,t.offset-r)),r=t.offset;if("start"==t.event)v+=s(t.node),A.push(t.node);else if("stop"==t.event){var B,a=A.length;do a--,B=A[a],v+="</"+B.nodeName.toLowerCase()+">";while(B!=t.node);for(A.splice(a,1);a<A.length;)v+=s(A[a]),a++}}k=
v+b(k.substr(r));q.value=k}j.value=u(j.value,g,e);g=h.className;g.match("(\\s|^)(language-)?"+n+"(\\s|$)")||(g=g?g+" "+n:n);/MSIE [678]/.test(navigator.userAgent)&&"CODE"==h.tagName&&"PRE"==h.parentNode.tagName?(i=h.parentNode,e=document.createElement("div"),e.innerHTML="<pre><code>"+j.value+"</code></pre>",h=e.firstChild.firstChild,e.firstChild.cN=i.cN,i.parentNode.replaceChild(e.firstChild,i)):h.innerHTML=j.value;h.className=g;h.result={language:n,kw:j.keyword_count,re:j.r};j.second_best&&(h.second_best=
{language:j.second_best.language,kw:j.second_best.keyword_count,re:j.second_best.r})}}function r(){if(!r.called){r.called=!0;for(var b=document.getElementsByTagName("pre"),d=0;d<b.length;d++){var e;a:{e=b[d];for(var f=0;f<e.childNodes.length;f++){var g=e.childNodes[f];if("CODE"==g.nodeName){e=g;break a}if(!(3==g.nodeType&&g.nodeValue.match(/\s+/)))break}e=void 0}e&&m(e,hljs.tabReplace)}}}var x={};this.LANGUAGES=x;this.highlight=l;this.highlightAuto=p;this.fixMarkup=u;this.highlightBlock=m;this.initHighlighting=
r;this.initHighlightingOnLoad=function(){window.addEventListener?(window.addEventListener("DOMContentLoaded",r,!1),window.addEventListener("load",r,!1)):window.attachEvent?window.attachEvent("onload",r):window.onload=r};this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BINARY_NUMBER_RE="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";
this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BINARY_NUMBER_MODE={cN:"number",b:this.BINARY_NUMBER_RE,r:0};this.inherit=function(b,d){var e={},f;for(f in b)e[f]=b[f];if(d)for(f in d)e[f]=d[f];return e}};
hljs.LANGUAGES.bash=function(){var b={"true":1,"false":1},g={cN:"variable",b:"\\$([a-zA-Z0-9_]+)\\b"},f={cN:"variable",b:"\\$\\{(([^}])|(\\\\}))+\\}",c:[hljs.CNM]},d={cN:"string",b:'"',e:'"',i:"\\n",c:[hljs.BE,g,f],r:0},i={cN:"string",b:"'",e:"'",r:0},l={cN:"test_condition",b:"",e:"",c:[d,i,g,f,hljs.CNM],k:{literal:b},r:0};return{dM:{k:{keyword:{"if":1,then:1,"else":1,fi:1,"for":1,"break":1,"continue":1,"while":1,"in":1,"do":1,done:1,echo:1,exit:1,"return":1,set:1,declare:1},literal:b},c:[{cN:"shebang",
b:"(#!\\/bin\\/bash)|(#!\\/bin\\/sh)",r:10},g,f,hljs.HCM,hljs.CNM,d,i,hljs.inherit(l,{b:"\\[ ",e:" \\]",r:0}),hljs.inherit(l,{b:"\\[\\[ ",e:" \\]\\]"})]}}}();
hljs.LANGUAGES.cs={dM:{k:{"abstract":1,as:1,base:1,bool:1,"break":1,"byte":1,"case":1,"catch":1,"char":1,checked:1,"class":1,"const":1,"continue":1,decimal:1,"default":1,delegate:1,"do":1,"double":1,"else":1,"enum":1,event:1,explicit:1,extern:1,"false":1,"finally":1,fixed:1,"float":1,"for":1,foreach:1,"goto":1,"if":1,implicit:1,"in":1,"int":1,"interface":1,internal:1,is:1,lock:1,"long":1,namespace:1,"new":1,"null":1,object:1,operator:1,out:1,override:1,params:1,"private":1,"protected":1,"public":1,
readonly:1,ref:1,"return":1,sbyte:1,sealed:1,"short":1,sizeof:1,stackalloc:1,"static":1,string:1,struct:1,"switch":1,"this":1,"throw":1,"true":1,"try":1,"typeof":1,uint:1,ulong:1,unchecked:1,unsafe:1,ushort:1,using:1,virtual:1,"volatile":1,"void":1,"while":1,ascending:1,descending:1,from:1,get:1,group:1,into:1,join:1,let:1,orderby:1,partial:1,select:1,set:1,value:1,"var":1,where:1,yield:1},c:[{cN:"comment",b:"///",e:"$",rB:!0,c:[{cN:"xmlDocTag",b:"///|<\!--|--\>"},{cN:"xmlDocTag",b:"</?",e:">"}]},
hljs.CLCM,hljs.CBLCLM,{cN:"preprocessor",b:"#",e:"$",k:{"if":1,"else":1,elif:1,endif:1,define:1,undef:1,warning:1,error:1,line:1,region:1,endregion:1,pragma:1,checksum:1}},{cN:"string",b:'@"',e:'"',c:[{b:'""'}]},hljs.ASM,hljs.QSM,hljs.CNM]}};
hljs.LANGUAGES.ruby=function(){var b={keyword:{and:1,"false":1,then:1,defined:1,module:1,"in":1,"return":1,redo:1,"if":1,BEGIN:1,retry:1,end:1,"for":1,"true":1,self:1,when:1,next:1,until:1,"do":1,begin:1,unless:1,END:1,rescue:1,nil:1,"else":1,"break":1,undef:1,not:1,"super":1,"class":1,"case":1,require:1,yield:1,alias:1,"while":1,ensure:1,elsif:1,or:1,def:1},keymethods:{__id__:1,__send__:1,abort:1,abs:1,"all?":1,allocate:1,ancestors:1,"any?":1,arity:1,assoc:1,at:1,at_exit:1,autoload:1,"autoload?":1,
"between?":1,binding:1,binmode:1,"block_given?":1,call:1,callcc:1,caller:1,capitalize:1,"capitalize!":1,casecmp:1,"catch":1,ceil:1,center:1,chomp:1,"chomp!":1,chop:1,"chop!":1,chr:1,"class":1,class_eval:1,"class_variable_defined?":1,class_variables:1,clear:1,clone:1,close:1,close_read:1,close_write:1,"closed?":1,coerce:1,collect:1,"collect!":1,compact:1,"compact!":1,concat:1,"const_defined?":1,const_get:1,const_missing:1,const_set:1,constants:1,count:1,crypt:1,"default":1,default_proc:1,"delete":1,
"delete!":1,delete_at:1,delete_if:1,detect:1,display:1,div:1,divmod:1,downcase:1,"downcase!":1,downto:1,dump:1,dup:1,each:1,each_byte:1,each_index:1,each_key:1,each_line:1,each_pair:1,each_value:1,each_with_index:1,"empty?":1,entries:1,eof:1,"eof?":1,"eql?":1,"equal?":1,eval:1,exec:1,exit:1,"exit!":1,extend:1,fail:1,fcntl:1,fetch:1,fileno:1,fill:1,find:1,find_all:1,first:1,flatten:1,"flatten!":1,floor:1,flush:1,for_fd:1,foreach:1,fork:1,format:1,freeze:1,"frozen?":1,fsync:1,getc:1,gets:1,global_variables:1,
grep:1,gsub:1,"gsub!":1,"has_key?":1,"has_value?":1,hash:1,hex:1,id:1,include:1,"include?":1,included_modules:1,index:1,indexes:1,indices:1,induced_from:1,inject:1,insert:1,inspect:1,instance_eval:1,instance_method:1,instance_methods:1,"instance_of?":1,"instance_variable_defined?":1,instance_variable_get:1,instance_variable_set:1,instance_variables:1,"integer?":1,intern:1,invert:1,ioctl:1,"is_a?":1,isatty:1,"iterator?":1,join:1,"key?":1,keys:1,"kind_of?":1,lambda:1,last:1,length:1,lineno:1,ljust:1,
load:1,local_variables:1,loop:1,lstrip:1,"lstrip!":1,map:1,"map!":1,match:1,max:1,"member?":1,merge:1,"merge!":1,method:1,"method_defined?":1,method_missing:1,methods:1,min:1,module_eval:1,modulo:1,name:1,nesting:1,"new":1,next:1,"next!":1,"nil?":1,nitems:1,"nonzero?":1,object_id:1,oct:1,open:1,pack:1,partition:1,pid:1,pipe:1,pop:1,popen:1,pos:1,prec:1,prec_f:1,prec_i:1,print:1,printf:1,private_class_method:1,private_instance_methods:1,"private_method_defined?":1,private_methods:1,proc:1,protected_instance_methods:1,
"protected_method_defined?":1,protected_methods:1,public_class_method:1,public_instance_methods:1,"public_method_defined?":1,public_methods:1,push:1,putc:1,puts:1,quo:1,raise:1,rand:1,rassoc:1,read:1,read_nonblock:1,readchar:1,readline:1,readlines:1,readpartial:1,rehash:1,reject:1,"reject!":1,remainder:1,reopen:1,replace:1,require:1,"respond_to?":1,reverse:1,"reverse!":1,reverse_each:1,rewind:1,rindex:1,rjust:1,round:1,rstrip:1,"rstrip!":1,scan:1,seek:1,select:1,send:1,set_trace_func:1,shift:1,singleton_method_added:1,
singleton_methods:1,size:1,sleep:1,slice:1,"slice!":1,sort:1,"sort!":1,sort_by:1,split:1,sprintf:1,squeeze:1,"squeeze!":1,srand:1,stat:1,step:1,store:1,strip:1,"strip!":1,sub:1,"sub!":1,succ:1,"succ!":1,sum:1,superclass:1,swapcase:1,"swapcase!":1,sync:1,syscall:1,sysopen:1,sysread:1,sysseek:1,system:1,syswrite:1,taint:1,"tainted?":1,tell:1,test:1,"throw":1,times:1,to_a:1,to_ary:1,to_f:1,to_hash:1,to_i:1,to_int:1,to_io:1,to_proc:1,to_s:1,to_str:1,to_sym:1,tr:1,"tr!":1,tr_s:1,"tr_s!":1,trace_var:1,
transpose:1,trap:1,truncate:1,"tty?":1,type:1,ungetc:1,uniq:1,"uniq!":1,unpack:1,unshift:1,untaint:1,untrace_var:1,upcase:1,"upcase!":1,update:1,upto:1,"value?":1,values:1,values_at:1,warn:1,write:1,write_nonblock:1,"zero?":1,zip:1}},g={cN:"yardoctag",b:"@[A-Za-z]+"},f=[{cN:"comment",b:"#",e:"$",c:[g]},{cN:"comment",b:"^\\=begin",e:"^\\=end",c:[g],r:10},{cN:"comment",b:"^__END__",e:"\\n$"}],g={cN:"subst",b:"#\\{",e:"}",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b},d=[hljs.BE,g],i=[{cN:"string",b:"'",
e:"'",c:d,r:0},{cN:"string",b:'"',e:'"',c:d,r:0},{cN:"string",b:"%[qw]?\\(",e:"\\)",c:d,r:10},{cN:"string",b:"%[qw]?\\[",e:"\\]",c:d,r:10},{cN:"string",b:"%[qw]?{",e:"}",c:d,r:10},{cN:"string",b:"%[qw]?<",e:">",c:d,r:10},{cN:"string",b:"%[qw]?/",e:"/",c:d,r:10},{cN:"string",b:"%[qw]?%",e:"%",c:d,r:10},{cN:"string",b:"%[qw]?-",e:"-",c:d,r:10},{cN:"string",b:"%[qw]?\\|",e:"\\|",c:d,r:10}],d={cN:"function",b:"\\bdef\\s+",e:" |$|;",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b,c:[{cN:"title",b:"[a-zA-Z_]\\w*[!?=]?|[-+~]\\@|<<|>>|=~|===?|<=>|[<>]=?|\\*\\*|[-/+%^&*~`|]|\\[\\]=?",
l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b},{cN:"params",b:"\\(",e:"\\)",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b}].concat(f)},l={cN:"identifier",b:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b,r:0},f=f.concat(i.concat([{cN:"class",b:"\\b(class|module)\\b",e:"$|;",k:{"class":1,module:1},c:[{cN:"title",b:"[A-Za-z_]\\w*(::\\w+)*(\\?|\\!)?",r:0},{cN:"inheritance",b:"<\\s*",c:[{cN:"parent",b:"("+hljs.IR+"::)?"+hljs.IR}]}].concat(f)},d,{cN:"constant",b:"(::)?([A-Z]\\w*(::)?)+",
r:0},{cN:"symbol",b:":",c:i.concat([l]),r:0},{cN:"number",b:"(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b",r:0},{cN:"number",b:"\\?\\w"},{cN:"variable",b:"(\\$\\W)|((\\$|\\@\\@?)(\\w+))"},l,{b:"("+hljs.RSR+")\\s*",c:f.concat([{cN:"regexp",b:"/",e:"/[a-z]*",i:"\\n",c:[hljs.BE]}]),r:0}]));g.c=f;d.c[1].c=f;return{dM:{l:"[a-zA-Z_][a-zA-Z0-9_]*(\\!|\\?)?",k:b,c:f}}}();
hljs.LANGUAGES.diff={cI:!0,dM:{c:[{cN:"chunk",b:"^\\@\\@ +\\-\\d+,\\d+ +\\+\\d+,\\d+ +\\@\\@$",r:10},{cN:"chunk",b:"^\\*\\*\\* +\\d+,\\d+ +\\*\\*\\*\\*$",r:10},{cN:"chunk",b:"^\\-\\-\\- +\\d+,\\d+ +\\-\\-\\-\\-$",r:10},{cN:"header",b:"Index: ",e:"$"},{cN:"header",b:"=====",e:"=====$"},{cN:"header",b:"^\\-\\-\\-",e:"$"},{cN:"header",b:"^\\*{3} ",e:"$"},{cN:"header",b:"^\\+\\+\\+",e:"$"},{cN:"header",b:"\\*{5}",e:"\\*{5}$"},{cN:"addition",b:"^\\+",e:"$"},{cN:"deletion",b:"^\\-",e:"$"},{cN:"change",
b:"^\\!",e:"$"}]}};
hljs.LANGUAGES.javascript={dM:{k:{keyword:{"in":1,"if":1,"for":1,"while":1,"finally":1,"var":1,"new":1,"function":1,"do":1,"return":1,"void":1,"else":1,"break":1,"catch":1,"instanceof":1,"with":1,"throw":1,"case":1,"default":1,"try":1,"this":1,"switch":1,"continue":1,"typeof":1,"delete":1},literal:{"true":1,"false":1,"null":1}},c:[hljs.ASM,hljs.QSM,hljs.CLCM,hljs.CBLCLM,hljs.CNM,{b:"("+hljs.RSR+"|case|return|throw)\\s*",k:{"return":1,"throw":1,"case":1},c:[hljs.CLCM,hljs.CBLCLM,{cN:"regexp",b:"/",
e:"/[gim]*",c:[{b:"\\\\/"}]}],r:0},{cN:"function",b:"\\bfunction\\b",e:"{",k:{"function":1},c:[{cN:"title",b:"[A-Za-z$_][0-9A-Za-z$_]*"},{cN:"params",b:"\\(",e:"\\)",c:[hljs.ASM,hljs.QSM,hljs.CLCM,hljs.CBLCLM]}]}]}};
hljs.LANGUAGES.css=function(){var b={cN:"function",b:hljs.IR+"\\(",e:"\\)",c:[{eW:!0,eE:!0,c:[hljs.NM,hljs.ASM,hljs.QSM]}]};return{cI:!0,dM:{i:"[=/|']",c:[hljs.CBLCLM,{cN:"id",b:"\\#[A-Za-z0-9_-]+"},{cN:"class",b:"\\.[A-Za-z0-9_-]+",r:0},{cN:"attr_selector",b:"\\[",e:"\\]",i:"$"},{cN:"pseudo",b:":(:)?[a-zA-Z0-9\\_\\-\\+\\(\\)\\\"\\']+"},{cN:"at_rule",b:"@(font-face|page)",l:"[a-z-]+",k:{"font-face":1,page:1}},{cN:"at_rule",b:"@",e:"[{;]",eE:!0,k:{"import":1,page:1,media:1,charset:1},c:[b,hljs.ASM,
hljs.QSM,hljs.NM]},{cN:"tag",b:hljs.IR,r:0},{cN:"rules",b:"{",e:"}",i:"[^\\s]",r:0,c:[hljs.CBLCLM,{cN:"rule",b:"[^\\s]",rB:!0,e:";",eW:!0,c:[{cN:"attribute",b:"[A-Z\\_\\.\\-]+",e:":",eE:!0,i:"[^\\s]",starts:{cN:"value",eW:!0,eE:!0,c:[b,hljs.NM,hljs.QSM,hljs.ASM,hljs.CBLCLM,{cN:"hexcolor",b:"\\#[0-9A-F]+"},{cN:"important",b:"!important"}]}}]}]}]}}}();
hljs.LANGUAGES.xml=function(){var b={eW:!0,c:[{cN:"attribute",b:"[A-Za-z0-9\\._:-]+",r:0},{b:'="',rB:!0,e:'"',c:[{cN:"value",b:'"',eW:!0}]},{b:"='",rB:!0,e:"'",c:[{cN:"value",b:"'",eW:!0}]},{b:"=",c:[{cN:"value",b:"[^\\s/>]+"}]}]};return{cI:!0,dM:{c:[{cN:"pi",b:"<\\?",e:"\\?>",r:10},{cN:"doctype",b:"<!DOCTYPE",e:">",r:10,c:[{b:"\\[",e:"\\]"}]},{cN:"comment",b:"<\!--",e:"--\>",r:10},{cN:"cdata",b:"<\\!\\[CDATA\\[",e:"\\]\\]>",r:10},{cN:"tag",b:"<style(?=\\s|>|$)",e:">",k:{title:{style:1}},c:[b],starts:{cN:"css",
e:"</style>",rE:!0,sL:"css"}},{cN:"tag",b:"<script(?=\\s|>|$)",e:">",k:{title:{script:1}},c:[b],starts:{cN:"javascript",e:"<\/script>",rE:!0,sL:"javascript"}},{cN:"vbscript",b:"<%",e:"%>",sL:"vbscript"},{cN:"tag",b:"</?",e:"/?>",c:[{cN:"title",b:"[^ />]+"},b]}]}}}();
hljs.LANGUAGES.java={dM:{k:{"false":1,"synchronized":1,"int":1,"abstract":1,"float":1,"private":1,"char":1,"interface":1,"boolean":1,"static":1,"null":1,"if":1,"const":1,"for":1,"true":1,"while":1,"long":1,"throw":1,strictfp:1,"finally":1,"protected":1,"extends":1,"import":1,"native":1,"final":1,"implements":1,"return":1,"void":1,"enum":1,"else":1,"break":1,"transient":1,"new":1,"catch":1,"instanceof":1,"byte":1,"super":1,"class":1,"volatile":1,"case":1,assert:1,"short":1,"package":1,"default":1,
"double":1,"public":1,"try":1,"this":1,"switch":1,"continue":1,"throws":1},c:[{cN:"javadoc",b:"/\\*\\*",e:"\\*/",c:[{cN:"javadoctag",b:"@[A-Za-z]+"}],r:10},hljs.CLCM,hljs.CBLCLM,hljs.ASM,hljs.QSM,{cN:"class",b:"(class |interface )",e:"{",k:{"class":1,"interface":1},i:":",c:[{b:"(implements|extends)",k:{"extends":1,"implements":1},r:10},{cN:"title",b:hljs.UIR}]},hljs.CNM,{cN:"annotation",b:"@[A-Za-z]+"}]}};
hljs.LANGUAGES.php={cI:!0,dM:{k:{and:1,include_once:1,list:1,"abstract":1,global:1,"private":1,echo:1,"interface":1,as:1,"static":1,endswitch:1,array:1,"null":1,"if":1,endwhile:1,or:1,"const":1,"for":1,endforeach:1,self:1,"var":1,"while":1,isset:1,"public":1,"protected":1,exit:1,foreach:1,"throw":1,elseif:1,"extends":1,include:1,__FILE__:1,empty:1,require_once:1,"function":1,"do":1,xor:1,"return":1,"implements":1,parent:1,clone:1,use:1,__CLASS__:1,__LINE__:1,"else":1,"break":1,print:1,eval:1,"new":1,
"catch":1,__METHOD__:1,"class":1,"case":1,exception:1,php_user_filter:1,"default":1,die:1,require:1,__FUNCTION__:1,enddeclare:1,"final":1,"try":1,"this":1,"switch":1,"continue":1,endfor:1,endif:1,declare:1,unset:1,"true":1,"false":1,namespace:1,trait:1,"goto":1,"instanceof":1,__DIR__:1,__NAMESPACE__:1,__halt_compiler:1},c:[hljs.CLCM,hljs.HCM,{cN:"comment",b:"/\\*",e:"\\*/",c:[{cN:"phpdoc",b:"\\s@[A-Za-z]+"}]},{cN:"comment",eB:!0,b:"__halt_compiler[^;]+;",e:"[\\n\\r]$"},hljs.CNM,hljs.BINARY_NUMBER_MODE,
hljs.inherit(hljs.ASM,{i:null}),hljs.inherit(hljs.QSM,{i:null}),{cN:"string",b:'b"',e:'"',c:[hljs.BE]},{cN:"string",b:"b'",e:"'",c:[hljs.BE]},{cN:"string",b:"<<<['\"]?\\w+['\"]?$",e:"^\\w+;",c:[hljs.BE]},{cN:"variable",b:"\\$+[a-zA-Z_\u007f-\u00ff][a-zA-Z0-9_\u007f-\u00ff]*"},{cN:"preprocessor",b:"<\\?php",r:10},{cN:"preprocessor",b:"\\?>"}]}};
hljs.LANGUAGES.python=function(){var b=[{cN:"string",b:"(u|b)?r?'''",e:"'''",r:10},{cN:"string",b:'(u|b)?r?"""',e:'"""',r:10},{cN:"string",b:"(u|r|ur)'",e:"'",c:[hljs.BE],r:10},{cN:"string",b:'(u|r|ur)"',e:'"',c:[hljs.BE],r:10},{cN:"string",b:"(b|br)'",e:"'",c:[hljs.BE]},{cN:"string",b:'(b|br)"',e:'"',c:[hljs.BE]}].concat([hljs.ASM,hljs.QSM]),g={cN:"title",b:hljs.UIR},f={cN:"params",b:"\\(",e:"\\)",c:b.concat([hljs.CNM])};return{dM:{k:{keyword:{and:1,elif:1,is:1,global:1,as:1,"in":1,"if":1,from:1,
raise:1,"for":1,except:1,"finally":1,print:1,"import":1,pass:1,"return":1,exec:1,"else":1,"break":1,not:1,"with":1,"class":1,assert:1,yield:1,"try":1,"while":1,"continue":1,del:1,or:1,def:1,lambda:1,nonlocal:10},built_in:{None:1,True:1,False:1,Ellipsis:1,NotImplemented:1}},i:"(</|->|\\?)",c:b.concat([hljs.HCM,{cN:"function",b:"\\bdef ",e:":",i:"$",k:{def:1},c:[g,f],r:10},{cN:"class",b:"\\bclass ",e:":",i:"[${]",k:{"class":1},c:[g,f],r:10},hljs.CNM,{cN:"decorator",b:"@",e:"$"}])}}}();
hljs.LANGUAGES.sql={cI:!0,dM:{i:"[^\\s]",c:[{cN:"operator",b:"(begin|start|commit|rollback|savepoint|lock|alter|create|drop|rename|call|delete|do|handler|insert|load|replace|select|truncate|update|set|show|pragma|grant)\\b",e:";|$",k:{keyword:{all:1,partial:1,global:1,month:1,current_timestamp:1,using:1,go:1,revoke:1,smallint:1,indicator:1,"end-exec":1,disconnect:1,zone:1,"with":1,character:1,assertion:1,to:1,add:1,current_user:1,usage:1,input:1,local:1,alter:1,match:1,collate:1,real:1,then:1,rollback:1,
get:1,read:1,timestamp:1,session_user:1,not:1,integer:1,bit:1,unique:1,day:1,minute:1,desc:1,insert:1,execute:1,like:1,ilike:2,level:1,decimal:1,drop:1,"continue":1,isolation:1,found:1,where:1,constraints:1,domain:1,right:1,national:1,some:1,module:1,transaction:1,relative:1,second:1,connect:1,escape:1,close:1,system_user:1,"for":1,deferred:1,section:1,cast:1,current:1,sqlstate:1,allocate:1,intersect:1,deallocate:1,numeric:1,"public":1,preserve:1,full:1,"goto":1,initially:1,asc:1,no:1,key:1,output:1,
collation:1,group:1,by:1,union:1,session:1,both:1,last:1,language:1,constraint:1,column:1,of:1,space:1,foreign:1,deferrable:1,prior:1,connection:1,unknown:1,action:1,commit:1,view:1,or:1,first:1,into:1,"float":1,year:1,primary:1,cascaded:1,except:1,restrict:1,set:1,references:1,names:1,table:1,outer:1,open:1,select:1,size:1,are:1,rows:1,from:1,prepare:1,distinct:1,leading:1,create:1,only:1,next:1,inner:1,authorization:1,schema:1,corresponding:1,option:1,declare:1,precision:1,immediate:1,"else":1,
timezone_minute:1,external:1,varying:1,translation:1,"true":1,"case":1,exception:1,join:1,hour:1,"default":1,"double":1,scroll:1,value:1,cursor:1,descriptor:1,values:1,dec:1,fetch:1,procedure:1,"delete":1,and:1,"false":1,"int":1,is:1,describe:1,"char":1,as:1,at:1,"in":1,varchar:1,"null":1,trailing:1,any:1,absolute:1,current_time:1,end:1,grant:1,privileges:1,when:1,cross:1,check:1,write:1,current_date:1,pad:1,begin:1,temporary:1,exec:1,time:1,update:1,catalog:1,user:1,sql:1,date:1,on:1,identity:1,
timezone_hour:1,natural:1,whenever:1,interval:1,work:1,order:1,cascade:1,diagnostics:1,nchar:1,having:1,left:1,call:1,"do":1,handler:1,load:1,replace:1,truncate:1,start:1,lock:1,show:1,pragma:1},aggregate:{count:1,sum:1,min:1,max:1,avg:1}},c:[{cN:"string",b:"'",e:"'",c:[hljs.BE,{b:"''"}],r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE,{b:'""'}],r:0},{cN:"string",b:"`",e:"`",c:[hljs.BE]},hljs.CNM,{b:"\\n"}]},hljs.CBLCLM,{cN:"comment",b:"--",e:"$"}]}};
hljs.LANGUAGES.ini={cI:!0,dM:{i:"[^\\s]",c:[{cN:"comment",b:";",e:"$"},{cN:"title",b:"^\\[",e:"\\]"},{cN:"setting",b:"^[a-z0-9_\\[\\]]+[ \\t]*=[ \\t]*",e:"$",c:[{cN:"value",eW:!0,k:{on:1,off:1,"true":1,"false":1,yes:1,no:1},c:[hljs.QSM,hljs.NM]}]}]}};
hljs.LANGUAGES.perl=function(){var b={getpwent:1,getservent:1,quotemeta:1,msgrcv:1,scalar:1,kill:1,dbmclose:1,undef:1,lc:1,ma:1,syswrite:1,tr:1,send:1,umask:1,sysopen:1,shmwrite:1,vec:1,qx:1,utime:1,local:1,oct:1,semctl:1,localtime:1,readpipe:1,"do":1,"return":1,format:1,read:1,sprintf:1,dbmopen:1,pop:1,getpgrp:1,not:1,getpwnam:1,rewinddir:1,qq:1,fileno:1,qw:1,endprotoent:1,wait:1,sethostent:1,bless:1,s:1,opendir:1,"continue":1,each:1,sleep:1,endgrent:1,shutdown:1,dump:1,chomp:1,connect:1,getsockname:1,
die:1,socketpair:1,close:1,flock:1,exists:1,index:1,shmget:1,sub:1,"for":1,endpwent:1,redo:1,lstat:1,msgctl:1,setpgrp:1,abs:1,exit:1,select:1,print:1,ref:1,gethostbyaddr:1,unshift:1,fcntl:1,syscall:1,"goto":1,getnetbyaddr:1,join:1,gmtime:1,symlink:1,semget:1,splice:1,x:1,getpeername:1,recv:1,log:1,setsockopt:1,cos:1,last:1,reverse:1,gethostbyname:1,getgrnam:1,study:1,formline:1,endhostent:1,times:1,chop:1,length:1,gethostent:1,getnetent:1,pack:1,getprotoent:1,getservbyname:1,rand:1,mkdir:1,pos:1,
chmod:1,y:1,substr:1,endnetent:1,printf:1,next:1,open:1,msgsnd:1,readdir:1,use:1,unlink:1,getsockopt:1,getpriority:1,rindex:1,wantarray:1,hex:1,system:1,getservbyport:1,endservent:1,"int":1,chr:1,untie:1,rmdir:1,prototype:1,tell:1,listen:1,fork:1,shmread:1,ucfirst:1,setprotoent:1,"else":1,sysseek:1,link:1,getgrgid:1,shmctl:1,waitpid:1,unpack:1,getnetbyname:1,reset:1,chdir:1,grep:1,split:1,require:1,caller:1,lcfirst:1,until:1,warn:1,"while":1,values:1,shift:1,telldir:1,getpwuid:1,my:1,getprotobynumber:1,
"delete":1,and:1,sort:1,uc:1,defined:1,srand:1,accept:1,"package":1,seekdir:1,getprotobyname:1,semop:1,our:1,rename:1,seek:1,"if":1,q:1,chroot:1,sysread:1,setpwent:1,no:1,crypt:1,getc:1,chown:1,sqrt:1,write:1,setnetent:1,setpriority:1,foreach:1,tie:1,sin:1,msgget:1,map:1,stat:1,getlogin:1,unless:1,elsif:1,truncate:1,exec:1,keys:1,glob:1,tied:1,closedir:1,ioctl:1,socket:1,readlink:1,eval:1,xor:1,readline:1,binmode:1,setservent:1,eof:1,ord:1,bind:1,alarm:1,pipe:1,atan2:1,getgrent:1,exp:1,time:1,push:1,
setgrent:1,gt:1,lt:1,or:1,ne:1,m:1},g={cN:"subst",b:"[$@]\\{",e:"\\}",k:b,r:10},f={cN:"variable",b:"\\$\\d"},d={cN:"variable",b:"[\\$\\%\\@\\*](\\^\\w\\b|#\\w+(\\:\\:\\w+)*|[^\\s\\w{]|{\\w+}|\\w+(\\:\\:\\w*)*)"},i=[hljs.BE,g,f,d],l={b:"->",c:[{b:hljs.IR},{b:"{",e:"}"}]},p={cN:"comment",b:"^(__END__|__DATA__)",e:"\\n$",r:5},f=[f,d,hljs.HCM,p,l,{cN:"string",b:"q[qwxr]?\\s*\\(",e:"\\)",c:i,r:5},{cN:"string",b:"q[qwxr]?\\s*\\[",e:"\\]",c:i,r:5},{cN:"string",b:"q[qwxr]?\\s*\\{",e:"\\}",c:i,r:5},{cN:"string",
b:"q[qwxr]?\\s*\\|",e:"\\|",c:i,r:5},{cN:"string",b:"q[qwxr]?\\s*\\<",e:"\\>",c:i,r:5},{cN:"string",b:"qw\\s+q",e:"q",c:i,r:5},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"string",b:'"',e:'"',c:i,r:0},{cN:"string",b:"`",e:"`",c:[hljs.BE]},{cN:"string",b:"{\\w+}",r:0},{cN:"string",b:"-?\\w+\\s*\\=\\>",r:0},{cN:"number",b:"(\\b0[0-7_]+)|(\\b0x[0-9a-fA-F_]+)|(\\b[1-9][0-9_]*(\\.[0-9_]+)?)|[0_]\\b",r:0},{b:"("+hljs.RSR+"|split|return|print|reverse|grep)\\s*",k:{split:1,"return":1,print:1,reverse:1,
grep:1},r:0,c:[hljs.HCM,p,{cN:"regexp",b:"(s|tr|y)/(\\\\.|[^/])*/(\\\\.|[^/])*/[a-z]*",r:10},{cN:"regexp",b:"(m|qr)?/",e:"/[a-z]*",c:[hljs.BE],r:0}]},{cN:"sub",b:"\\bsub\\b",e:"(\\s*\\(.*?\\))?[;{]",k:{sub:1},r:5},{cN:"operator",b:"-\\w\\b",r:0},{cN:"pod",b:"\\=\\w",e:"\\=cut"}];g.c=f;l.c[1].c=f;return{dM:{k:b,c:f}}}();
hljs.LANGUAGES.objectivec=function(){return{dM:{k:{keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,sizeof:2,typedef:2,"const":1,struct:1,"for":1,union:1,unsigned:1,"long":1,"volatile":2,"static":1,"protected":1,bool:1,mutable:1,"if":1,"public":1,"do":1,"return":1,"goto":1,"void":2,"enum":1,"else":1,"break":1,extern:1,"true":1,"class":1,asm:1,"case":1,"short":1,"default":1,"double":1,"throw":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,
"continue":1,wchar_t:1,inline:1,readonly:1,assign:1,property:1,protocol:10,self:1,"synchronized":1,end:1,synthesize:50,id:1,optional:1,required:1,implementation:10,nonatomic:1,"interface":1,"super":1,unichar:1,"finally":2,dynamic:2,nil:1},built_in:{YES:5,NO:5,NULL:1,IBOutlet:50,IBAction:50,NSString:50,NSDictionary:50,CGRect:50,CGPoint:50,NSRange:50,release:1,retain:1,autorelease:50,UIButton:50,UILabel:50,UITextView:50,UIWebView:50,MKMapView:50,UISegmentedControl:50,NSObject:50,UITableViewDelegate:50,
UITableViewDataSource:50,NSThread:50,UIActivityIndicator:50,UITabbar:50,UIToolBar:50,UIBarButtonItem:50,UIImageView:50,NSAutoreleasePool:50,UITableView:50,BOOL:1,NSInteger:20,CGFloat:20,NSException:50,NSLog:50,NSMutableString:50,NSMutableArray:50,NSMutableDictionary:50,NSURL:50}},i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.CNM,hljs.QSM,{cN:"string",b:"'",e:"[^\\\\]'",i:"[^\\\\][^']"},{cN:"preprocessor",b:"#import",e:"$",c:[{cN:"title",b:'"',e:'"'},{cN:"title",b:"<",e:">"}]},{cN:"preprocessor",b:"#",e:"$"},
{cN:"class",b:"interface|class|protocol|implementation",e:"({|$)",k:{"interface":1,"class":1,protocol:5,implementation:5},c:[{cN:"id",b:hljs.UIR}]}]}}}();
hljs.LANGUAGES.coffeescript=function(){var b={keyword:{"in":1,"if":1,"for":1,"while":1,"finally":1,"new":1,"do":1,"return":1,"else":1,"break":1,"catch":1,"instanceof":1,"throw":1,"try":1,"this":1,"switch":1,"continue":1,"typeof":1,"delete":1,"debugger":1,"class":1,"extends":1,"super":1,then:1,unless:1,until:1,loop:2,of:2,by:1,when:2,and:1,or:1,is:1,isnt:2,not:1},literal:{"true":1,"false":1,"null":1,undefined:1,yes:1,no:1,on:1,off:1},reserved:{"case":1,"default":1,"function":1,"var":1,"void":1,"with":1,
"const":1,let:1,"enum":1,"export":1,"import":1,"native":1,__hasProp:1,__extends:1,__slice:1,__bind:1,__indexOf:1}},g={cN:"subst",b:"#\\{",e:"}",k:b,c:[hljs.CNM,hljs.BINARY_NUMBER_MODE]};return{dM:{k:b,c:[hljs.CNM,hljs.BINARY_NUMBER_MODE,hljs.ASM,{cN:"string",b:'"""',e:'"""',c:[hljs.BE,g]},{cN:"string",b:'"',e:'"',r:0,c:[hljs.BE,g]},{cN:"comment",b:"###",e:"###"},hljs.HCM,{cN:"regexp",b:"///",e:"///",c:[hljs.HCM]},{cN:"javascript",b:"`",e:"`",eB:!0,eE:!0,sL:"javascript"},{cN:"function",b:"[A-Za-z$_][0-9A-Za-z$_]*\\s*=\\s*(\\(.+\\))?\\s*[-=]>",
rB:!0,c:[{cN:"title",b:"[A-Za-z$_][0-9A-Za-z$_]*"},{cN:"params",b:"\\(",e:"\\)"}]}]}}}();
hljs.LANGUAGES.apache=function(){var b={cN:"number",b:"[\\$%]\\d+"};return{cI:!0,dM:{k:{keyword:{acceptfilter:1,acceptmutex:1,acceptpathinfo:1,accessfilename:1,action:1,addalt:1,addaltbyencoding:1,addaltbytype:1,addcharset:1,adddefaultcharset:1,adddescription:1,addencoding:1,addhandler:1,addicon:1,addiconbyencoding:1,addiconbytype:1,addinputfilter:1,addlanguage:1,addmoduleinfo:1,addoutputfilter:1,addoutputfilterbytype:1,addtype:1,alias:1,aliasmatch:1,allow:1,allowconnect:1,allowencodedslashes:1,allowoverride:1,
anonymous:1,anonymous_logemail:1,anonymous_mustgiveemail:1,anonymous_nouserid:1,anonymous_verifyemail:1,authbasicauthoritative:1,authbasicprovider:1,authdbduserpwquery:1,authdbduserrealmquery:1,authdbmgroupfile:1,authdbmtype:1,authdbmuserfile:1,authdefaultauthoritative:1,authdigestalgorithm:1,authdigestdomain:1,authdigestnccheck:1,authdigestnonceformat:1,authdigestnoncelifetime:1,authdigestprovider:1,authdigestqop:1,authdigestshmemsize:1,authgroupfile:1,authldapbinddn:1,authldapbindpassword:1,authldapcharsetconfig:1,
authldapcomparednonserver:1,authldapdereferencealiases:1,authldapgroupattribute:1,authldapgroupattributeisdn:1,authldapremoteuserattribute:1,authldapremoteuserisdn:1,authldapurl:1,authname:1,authnprovideralias:1,authtype:1,authuserfile:1,authzdbmauthoritative:1,authzdbmtype:1,authzdefaultauthoritative:1,authzgroupfileauthoritative:1,authzldapauthoritative:1,authzownerauthoritative:1,authzuserauthoritative:1,balancermember:1,browsermatch:1,browsermatchnocase:1,bufferedlogs:1,cachedefaultexpire:1,cachedirlength:1,
cachedirlevels:1,cachedisable:1,cacheenable:1,cachefile:1,cacheignorecachecontrol:1,cacheignoreheaders:1,cacheignorenolastmod:1,cacheignorequerystring:1,cachelastmodifiedfactor:1,cachemaxexpire:1,cachemaxfilesize:1,cacheminfilesize:1,cachenegotiateddocs:1,cacheroot:1,cachestorenostore:1,cachestoreprivate:1,cgimapextension:1,charsetdefault:1,charsetoptions:1,charsetsourceenc:1,checkcaseonly:1,checkspelling:1,chrootdir:1,contentdigest:1,cookiedomain:1,cookieexpires:1,cookielog:1,cookiename:1,cookiestyle:1,
cookietracking:1,coredumpdirectory:1,customlog:1,dav:1,davdepthinfinity:1,davgenericlockdb:1,davlockdb:1,davmintimeout:1,dbdexptime:1,dbdkeep:1,dbdmax:1,dbdmin:1,dbdparams:1,dbdpersist:1,dbdpreparesql:1,dbdriver:1,defaulticon:1,defaultlanguage:1,defaulttype:1,deflatebuffersize:1,deflatecompressionlevel:1,deflatefilternote:1,deflatememlevel:1,deflatewindowsize:1,deny:1,directoryindex:1,directorymatch:1,directoryslash:1,documentroot:1,dumpioinput:1,dumpiologlevel:1,dumpiooutput:1,enableexceptionhook:1,
enablemmap:1,enablesendfile:1,errordocument:1,errorlog:1,example:1,expiresactive:1,expiresbytype:1,expiresdefault:1,extendedstatus:1,extfilterdefine:1,extfilteroptions:1,fileetag:1,filterchain:1,filterdeclare:1,filterprotocol:1,filterprovider:1,filtertrace:1,forcelanguagepriority:1,forcetype:1,forensiclog:1,gracefulshutdowntimeout:1,group:1,header:1,headername:1,hostnamelookups:1,identitycheck:1,identitychecktimeout:1,imapbase:1,imapdefault:1,imapmenu:1,include:1,indexheadinsert:1,indexignore:1,indexoptions:1,
indexorderdefault:1,indexstylesheet:1,isapiappendlogtoerrors:1,isapiappendlogtoquery:1,isapicachefile:1,isapifakeasync:1,isapilognotsupported:1,isapireadaheadbuffer:1,keepalive:1,keepalivetimeout:1,languagepriority:1,ldapcacheentries:1,ldapcachettl:1,ldapconnectiontimeout:1,ldapopcacheentries:1,ldapopcachettl:1,ldapsharedcachefile:1,ldapsharedcachesize:1,ldaptrustedclientcert:1,ldaptrustedglobalcert:1,ldaptrustedmode:1,ldapverifyservercert:1,limitinternalrecursion:1,limitrequestbody:1,limitrequestfields:1,
limitrequestfieldsize:1,limitrequestline:1,limitxmlrequestbody:1,listen:1,listenbacklog:1,loadfile:1,loadmodule:1,lockfile:1,logformat:1,loglevel:1,maxclients:1,maxkeepaliverequests:1,maxmemfree:1,maxrequestsperchild:1,maxrequestsperthread:1,maxspareservers:1,maxsparethreads:1,maxthreads:1,mcachemaxobjectcount:1,mcachemaxobjectsize:1,mcachemaxstreamingbuffer:1,mcacheminobjectsize:1,mcacheremovalalgorithm:1,mcachesize:1,metadir:1,metafiles:1,metasuffix:1,mimemagicfile:1,minspareservers:1,minsparethreads:1,
mmapfile:1,mod_gzip_on:1,mod_gzip_add_header_count:1,mod_gzip_keep_workfiles:1,mod_gzip_dechunk:1,mod_gzip_min_http:1,mod_gzip_minimum_file_size:1,mod_gzip_maximum_file_size:1,mod_gzip_maximum_inmem_size:1,mod_gzip_temp_dir:1,mod_gzip_item_include:1,mod_gzip_item_exclude:1,mod_gzip_command_version:1,mod_gzip_can_negotiate:1,mod_gzip_handle_methods:1,mod_gzip_static_suffix:1,mod_gzip_send_vary:1,mod_gzip_update_static:1,modmimeusepathinfo:1,multiviewsmatch:1,namevirtualhost:1,noproxy:1,nwssltrustedcerts:1,
nwsslupgradeable:1,options:1,order:1,passenv:1,pidfile:1,protocolecho:1,proxybadheader:1,proxyblock:1,proxydomain:1,proxyerroroverride:1,proxyftpdircharset:1,proxyiobuffersize:1,proxymaxforwards:1,proxypass:1,proxypassinterpolateenv:1,proxypassmatch:1,proxypassreverse:1,proxypassreversecookiedomain:1,proxypassreversecookiepath:1,proxypreservehost:1,proxyreceivebuffersize:1,proxyremote:1,proxyremotematch:1,proxyrequests:1,proxyset:1,proxystatus:1,proxytimeout:1,proxyvia:1,readmename:1,receivebuffersize:1,
redirect:1,redirectmatch:1,redirectpermanent:1,redirecttemp:1,removecharset:1,removeencoding:1,removehandler:1,removeinputfilter:1,removelanguage:1,removeoutputfilter:1,removetype:1,requestheader:1,require:2,rewritebase:1,rewritecond:10,rewriteengine:1,rewritelock:1,rewritelog:1,rewriteloglevel:1,rewritemap:1,rewriteoptions:1,rewriterule:10,rlimitcpu:1,rlimitmem:1,rlimitnproc:1,satisfy:1,scoreboardfile:1,script:1,scriptalias:1,scriptaliasmatch:1,scriptinterpretersource:1,scriptlog:1,scriptlogbuffer:1,
scriptloglength:1,scriptsock:1,securelisten:1,seerequesttail:1,sendbuffersize:1,serveradmin:1,serveralias:1,serverlimit:1,servername:1,serverpath:1,serverroot:1,serversignature:1,servertokens:1,setenv:1,setenvif:1,setenvifnocase:1,sethandler:1,setinputfilter:1,setoutputfilter:1,ssienableaccess:1,ssiendtag:1,ssierrormsg:1,ssistarttag:1,ssitimeformat:1,ssiundefinedecho:1,sslcacertificatefile:1,sslcacertificatepath:1,sslcadnrequestfile:1,sslcadnrequestpath:1,sslcarevocationfile:1,sslcarevocationpath:1,
sslcertificatechainfile:1,sslcertificatefile:1,sslcertificatekeyfile:1,sslciphersuite:1,sslcryptodevice:1,sslengine:1,sslhonorciperorder:1,sslmutex:1,ssloptions:1,sslpassphrasedialog:1,sslprotocol:1,sslproxycacertificatefile:1,sslproxycacertificatepath:1,sslproxycarevocationfile:1,sslproxycarevocationpath:1,sslproxyciphersuite:1,sslproxyengine:1,sslproxymachinecertificatefile:1,sslproxymachinecertificatepath:1,sslproxyprotocol:1,sslproxyverify:1,sslproxyverifydepth:1,sslrandomseed:1,sslrequire:1,
sslrequiressl:1,sslsessioncache:1,sslsessioncachetimeout:1,sslusername:1,sslverifyclient:1,sslverifydepth:1,startservers:1,startthreads:1,substitute:1,suexecusergroup:1,threadlimit:1,threadsperchild:1,threadstacksize:1,timeout:1,traceenable:1,transferlog:1,typesconfig:1,unsetenv:1,usecanonicalname:1,usecanonicalphysicalport:1,user:1,userdir:1,virtualdocumentroot:1,virtualdocumentrootip:1,virtualscriptalias:1,virtualscriptaliasip:1,win32disableacceptex:1,xbithack:1},literal:{on:1,off:1}},c:[hljs.HCM,
{cN:"sqbracket",b:"\\s\\[",e:"\\]$"},{cN:"cbracket",b:"[\\$%]\\{",e:"\\}",c:["self",b]},b,{cN:"tag",b:"</?",e:">"},hljs.QSM]}}}();
hljs.LANGUAGES.cpp=function(){var b={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,
typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,
unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:b,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:b,r:10,c:["self"]}]}}}();
